//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_skill.hxx
// Note: requires additional types generated from: message_guid.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"skill_equip_info")]
  public partial class skill_equip_info : global::ProtoBuf.IExtensible
  {
    public skill_equip_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _equip_id = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"equip_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equip_id
    {
      get { return _equip_id; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_skill_op")]
  public partial class request_skill_op : global::ProtoBuf.IExtensible
  {
    public request_skill_op() {}
    
    private int _op_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skill_idx = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skill_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skill_idx
    {
      get { return _skill_idx; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _default_equip_idx = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"default_equip_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> default_equip_idx
    {
      get { return _default_equip_idx; }
    }
  

    private skill_equip_info _equip_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"equip_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public skill_equip_info equip_info
    {
      get { return _equip_info; }
      set { _equip_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_skill_op")]
  public partial class respond_skill_op : global::ProtoBuf.IExtensible
  {
    public respond_skill_op() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _skill_idx = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"skill_idx", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skill_idx
    {
      get { return _skill_idx; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _skill_level = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"skill_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> skill_level
    {
      get { return _skill_level; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SKILL_OP_TYPE")]
    public enum SKILL_OP_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_OP_EQUIP", Value=0)]
      SKILL_OP_EQUIP = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_OP_LEVEL", Value=1)]
      SKILL_OP_LEVEL = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SKILL_OP_UNLOCK_WEAPON_SKILL", Value=2)]
      SKILL_OP_UNLOCK_WEAPON_SKILL = 2
    }
  
}