//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_enum.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"messageid_enum_output")]
  public partial class messageid_enum_output : global::ProtoBuf.IExtensible
  {
    public messageid_enum_output() {}
    
    private int _ingore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ingore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ingore
    {
      get { return _ingore; }
      set { _ingore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"MESSAGE_ID")]
    public enum MESSAGE_ID
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CORE_BEING", Value=0)]
      ID_MSG_CORE_BEING = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_LOGIN", Value=1)]
      ID_MSG_LOGIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_GM", Value=2)]
      ID_MSG_GM = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CREATE_ROLE", Value=3)]
      ID_MSG_CREATE_ROLE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ENTER_GAME", Value=4)]
      ID_MSG_ENTER_GAME = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_NEW_SESSION", Value=5)]
      ID_MSG_NEW_SESSION = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_HEARBEAT", Value=6)]
      ID_MSG_HEARBEAT = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CORE_END", Value=99)]
      ID_MSG_CORE_END = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SCENE_ENTER", Value=100)]
      ID_MSG_SCENE_ENTER = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SCENE_PASS", Value=101)]
      ID_MSG_SCENE_PASS = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SCENE_AWARD", Value=102)]
      ID_MSG_SCENE_AWARD = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SCENE_RELIVE", Value=103)]
      ID_MSG_SCENE_RELIVE = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SCENE_UNLOCK", Value=104)]
      ID_MSG_SCENE_UNLOCK = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SKILL", Value=120)]
      ID_MSG_SKILL = 120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ARENA_RECORD", Value=150)]
      ID_MSG_ARENA_RECORD = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ARENA_REFRESH", Value=151)]
      ID_MSG_ARENA_REFRESH = 151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ARENA_BEGIN", Value=152)]
      ID_MSG_ARENA_BEGIN = 152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ARENA_END", Value=153)]
      ID_MSG_ARENA_END = 153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ARENA_BUYTIMES", Value=154)]
      ID_MSG_ARENA_BUYTIMES = 154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUALIFYING_RECORD", Value=160)]
      ID_MSG_QUALIFYING_RECORD = 160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUALIFYING_LIST", Value=161)]
      ID_MSG_QUALIFYING_LIST = 161,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUALIFYING_BEGIN", Value=162)]
      ID_MSG_QUALIFYING_BEGIN = 162,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUALIFYING_END", Value=163)]
      ID_MSG_QUALIFYING_END = 163,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUALIFYING_BUYTIMES", Value=164)]
      ID_MSG_QUALIFYING_BUYTIMES = 164,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SP_INCREASE", Value=200)]
      ID_MSG_SP_INCREASE = 200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_YAZHIXIEE_REPORT", Value=210)]
      ID_MSG_YAZHIXIEE_REPORT = 210,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_YAZHIXIEE_OVER", Value=211)]
      ID_MSG_YAZHIXIEE_OVER = 211,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ZHAOCAIMAO_REPORT", Value=220)]
      ID_MSG_ZHAOCAIMAO_REPORT = 220,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ZHAOCAIMAO_OVER", Value=221)]
      ID_MSG_ZHAOCAIMAO_OVER = 221,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ZHAOCAIMAO_PARTNER", Value=222)]
      ID_MSG_ZHAOCAIMAO_PARTNER = 222,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ZHAOCAIMAO_RANKING", Value=223)]
      ID_MSG_ZHAOCAIMAO_RANKING = 223,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WEAPON_DEPOT_BEGIN", Value=1000)]
      ID_MSG_WEAPON_DEPOT_BEGIN = 1000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WD_BUY_WEAPON", Value=1001)]
      ID_MSG_WD_BUY_WEAPON = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WD_CHANGE_WEAPON", Value=1002)]
      ID_MSG_WD_CHANGE_WEAPON = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WD_STREN_WEAPON", Value=1003)]
      ID_MSG_WD_STREN_WEAPON = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WD_SET_PROMOTE", Value=1004)]
      ID_MSG_WD_SET_PROMOTE = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WD_BAP_FITTINGS", Value=1005)]
      ID_MSG_WD_BAP_FITTINGS = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WEAPON_DEPOT_END", Value=2000)]
      ID_MSG_WEAPON_DEPOT_END = 2000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CHALLENGE_STAGE_BEGIN", Value=2001)]
      ID_MSG_CHALLENGE_STAGE_BEGIN = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CHALLENGE_STAGE_END", Value=2002)]
      ID_MSG_CHALLENGE_STAGE_END = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CHALLENGE_STAGE_CONTINUE", Value=2003)]
      ID_MSG_CHALLENGE_STAGE_CONTINUE = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CHALLENGE_STAGE_SWEEP", Value=2004)]
      ID_MSG_CHALLENGE_STAGE_SWEEP = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CHALLENGE_RANK", Value=2005)]
      ID_MSG_CHALLENGE_RANK = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUEST_ACCPET", Value=2100)]
      ID_MSG_QUEST_ACCPET = 2100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUEST_FINISH", Value=2101)]
      ID_MSG_QUEST_FINISH = 2101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WING_ACTIVE", Value=2102)]
      ID_MSG_WING_ACTIVE = 2102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WING_FORGE", Value=2103)]
      ID_MSG_WING_FORGE = 2103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WING_EQUIP", Value=2104)]
      ID_MSG_WING_EQUIP = 2104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_WING_UPDATE", Value=2105)]
      ID_MSG_WING_UPDATE = 2105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_FASHION_ACTIVE", Value=2106)]
      ID_MSG_FASHION_ACTIVE = 2106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_FASHION_ADDSTAR", Value=2107)]
      ID_MSG_FASHION_ADDSTAR = 2107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_FASHION_EQUIP", Value=2108)]
      ID_MSG_FASHION_EQUIP = 2108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_MALL_BUY", Value=2200)]
      ID_MSG_MALL_BUY = 2200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_BEGIN", Value=2300)]
      ID_MSG_DEFENCE_BEGIN = 2300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_STEN", Value=2301)]
      ID_MSG_DEFENCE_STEN = 2301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_RISING_STAR", Value=2302)]
      ID_MSG_DEFENCE_RISING_STAR = 2302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_PROMOTE", Value=2303)]
      ID_MSG_DEFENCE_PROMOTE = 2303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_STONE_INLAY", Value=2304)]
      ID_MSG_DEFENCE_STONE_INLAY = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_STONE_UNINLAY", Value=2305)]
      ID_MSG_DEFENCE_STONE_UNINLAY = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_STONE_COMB", Value=2306)]
      ID_MSG_DEFENCE_STONE_COMB = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_SALE", Value=2307)]
      ID_MSG_DEFENCE_SALE = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DEFENCE_END", Value=2399)]
      ID_MSG_DEFENCE_END = 2399,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ACTIVITY_BEGIN", Value=2400)]
      ID_MSG_ACTIVITY_BEGIN = 2400,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ACTIVITY_JOIN", Value=2401)]
      ID_MSG_ACTIVITY_JOIN = 2401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ACTIVITY_END", Value=2499)]
      ID_MSG_ACTIVITY_END = 2499,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ITEM_SALE", Value=2500)]
      ID_MSG_ITEM_SALE = 2500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ITEM_EQUIP", Value=2599)]
      ID_MSG_ITEM_EQUIP = 2599,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QIANGLINDANYU_BEGIN", Value=2600)]
      ID_MSG_QIANGLINDANYU_BEGIN = 2600,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QIANGLINDANYU_REPORT_SCORE", Value=2601)]
      ID_MSG_QIANGLINDANYU_REPORT_SCORE = 2601,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QIANGLINDANYU_OVER", Value=2602)]
      ID_MSG_QIANGLINDANYU_OVER = 2602,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QIANGLINDANYU_END", Value=2699)]
      ID_MSG_QIANGLINDANYU_END = 2699,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_BAG_OPERATION", Value=2700)]
      ID_MSG_BAG_OPERATION = 2700,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SHOP", Value=2800)]
      ID_MSG_SHOP = 2800,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_RANKING", Value=2900)]
      ID_MSG_RANKING = 2900,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_DAILY_RESET", Value=3000)]
      ID_MSG_DAILY_RESET = 3000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_EGG", Value=3100)]
      ID_MSG_EGG = 3100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_RANDOM_NAME", Value=4000)]
      ID_MSG_RANDOM_NAME = 4000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_MAIL_STATE_DELETE", Value=4100)]
      ID_MSG_MAIL_STATE_DELETE = 4100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_MAIL_STATE_OPENED", Value=4101)]
      ID_MSG_MAIL_STATE_OPENED = 4101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_MAIL_STATE_PICKED", Value=4102)]
      ID_MSG_MAIL_STATE_PICKED = 4102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_MAIL_LOAD", Value=4103)]
      ID_MSG_MAIL_LOAD = 4103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_TITLE", Value=4200)]
      ID_MSG_TITLE = 4200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_ZONE_REWARD", Value=5000)]
      ID_MSG_ZONE_REWARD = 5000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CROPS_BUY", Value=5001)]
      ID_MSG_CROPS_BUY = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CROPS_CHANGE", Value=5002)]
      ID_MSG_CROPS_CHANGE = 5002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_CROPS_PROMOTE", Value=5003)]
      ID_MSG_CROPS_PROMOTE = 5003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_SEVEN_AWARD_STAGE", Value=5004)]
      ID_MSG_SEVEN_AWARD_STAGE = 5004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_PLAYER_PLAN_STAGE", Value=5050)]
      ID_MSG_PLAYER_PLAN_STAGE = 5050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_FUND", Value=5100)]
      ID_MSG_FUND = 5100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_REQUEST_OTHER", Value=5200)]
      ID_MSG_REQUEST_OTHER = 5200,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_TOTALCHARGE", Value=5300)]
      ID_MSG_TOTALCHARGE = 5300,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_QUERY_RECHARGE_RESULT", Value=6000)]
      ID_MSG_QUERY_RECHARGE_RESULT = 6000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_FIRST_CHARGE_REWARD", Value=6100)]
      ID_MSG_FIRST_CHARGE_REWARD = 6100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ID_MSG_BOX_ITEM", Value=6200)]
      ID_MSG_BOX_ITEM = 6200
    }
  
}