//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message.hxx
// Note: requires additional types generated from: message_guid.hxx
// Note: requires additional types generated from: message_property.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_session")]
  public partial class request_session : global::ProtoBuf.IExtensible
  {
    public request_session() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_session")]
  public partial class respond_session : global::ProtoBuf.IExtensible
  {
    public respond_session() {}
    
    private uint _sessionid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sessionid
    {
      get { return _sessionid; }
      set { _sessionid = value; }
    }
    private string _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_login")]
  public partial class request_login : global::ProtoBuf.IExtensible
  {
    public request_login() {}
    
    private string _usrname;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"usrname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string usrname
    {
      get { return _usrname; }
      set { _usrname = value; }
    }
    private string _passwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passwd
    {
      get { return _passwd; }
      set { _passwd = value; }
    }
    private bool _tencentlogin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tencentlogin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool tencentlogin
    {
      get { return _tencentlogin; }
      set { _tencentlogin = value; }
    }

    private string _openId = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"openId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openId
    {
      get { return _openId; }
      set { _openId = value; }
    }

    private string _platform = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }

    private string _accesstoken = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"accesstoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accesstoken
    {
      get { return _accesstoken; }
      set { _accesstoken = value; }
    }

    private string _paytoken = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"paytoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paytoken
    {
      get { return _paytoken; }
      set { _paytoken = value; }
    }

    private string _pf = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pf
    {
      get { return _pf; }
      set { _pf = value; }
    }

    private string _pfkey = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pfkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pfkey
    {
      get { return _pfkey; }
      set { _pfkey = value; }
    }

    private uint _regchannel = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"regchannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regchannel
    {
      get { return _regchannel; }
      set { _regchannel = value; }
    }

    private uint _setupchannel = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"setupchannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint setupchannel
    {
      get { return _setupchannel; }
      set { _setupchannel = value; }
    }

    private string _clientsystem = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"clientsystem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientsystem
    {
      get { return _clientsystem; }
      set { _clientsystem = value; }
    }

    private string _txplat = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"txplat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string txplat
    {
      get { return _txplat; }
      set { _txplat = value; }
    }

    private string _clientversion = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"clientversion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientversion
    {
      get { return _clientversion; }
      set { _clientversion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_login")]
  public partial class respond_login : global::ProtoBuf.IExtensible
  {
    public respond_login() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private MSGGuild _charguid = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charguid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MSGGuild charguid
    {
      get { return _charguid; }
      set { _charguid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_create_role")]
  public partial class request_create_role : global::ProtoBuf.IExtensible
  {
    public request_create_role() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _resid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint resid
    {
      get { return _resid; }
      set { _resid = value; }
    }

    private string _openId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"openId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openId
    {
      get { return _openId; }
      set { _openId = value; }
    }

    private string _platform = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }

    private string _accesstoken = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"accesstoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accesstoken
    {
      get { return _accesstoken; }
      set { _accesstoken = value; }
    }

    private string _paytoken = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"paytoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paytoken
    {
      get { return _paytoken; }
      set { _paytoken = value; }
    }

    private string _pf = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pf
    {
      get { return _pf; }
      set { _pf = value; }
    }

    private string _pfkey = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"pfkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pfkey
    {
      get { return _pfkey; }
      set { _pfkey = value; }
    }

    private uint _regchannel = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"regchannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regchannel
    {
      get { return _regchannel; }
      set { _regchannel = value; }
    }

    private uint _setupchannel = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"setupchannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint setupchannel
    {
      get { return _setupchannel; }
      set { _setupchannel = value; }
    }

    private string _clientsystem = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"clientsystem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientsystem
    {
      get { return _clientsystem; }
      set { _clientsystem = value; }
    }

    private string _txplat = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"txplat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string txplat
    {
      get { return _txplat; }
      set { _txplat = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_create_role")]
  public partial class respond_create_role : global::ProtoBuf.IExtensible
  {
    public respond_create_role() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private MSGGuild _charguid = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"charguid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MSGGuild charguid
    {
      get { return _charguid; }
      set { _charguid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_enter_game")]
  public partial class request_enter_game : global::ProtoBuf.IExtensible
  {
    public request_enter_game() {}
    
    private MSGGuild _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }

    private string _openId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"openId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string openId
    {
      get { return _openId; }
      set { _openId = value; }
    }

    private string _platform = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"platform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string platform
    {
      get { return _platform; }
      set { _platform = value; }
    }

    private string _accesstoken = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"accesstoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accesstoken
    {
      get { return _accesstoken; }
      set { _accesstoken = value; }
    }

    private string _paytoken = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"paytoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string paytoken
    {
      get { return _paytoken; }
      set { _paytoken = value; }
    }

    private string _pf = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"pf", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pf
    {
      get { return _pf; }
      set { _pf = value; }
    }

    private string _pfkey = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"pfkey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pfkey
    {
      get { return _pfkey; }
      set { _pfkey = value; }
    }

    private string _clientsystem = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"clientsystem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string clientsystem
    {
      get { return _clientsystem; }
      set { _clientsystem = value; }
    }

    private string _txplat = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"txplat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string txplat
    {
      get { return _txplat; }
      set { _txplat = value; }
    }

    private uint _regchannel = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"regchannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint regchannel
    {
      get { return _regchannel; }
      set { _regchannel = value; }
    }

    private uint _setupchannel = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"setupchannel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint setupchannel
    {
      get { return _setupchannel; }
      set { _setupchannel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_enter_game")]
  public partial class respond_enter_game : global::ProtoBuf.IExtensible
  {
    public respond_enter_game() {}
    
    private uint _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result; }
      set { _result = value; }
    }

    private MSGGuild _guid = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }

    private role_property _prop = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"prop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_property prop
    {
      get { return _prop; }
      set { _prop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_new_session")]
  public partial class request_new_session : global::ProtoBuf.IExtensible
  {
    public request_new_session() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_new_session")]
  public partial class respond_new_session : global::ProtoBuf.IExtensible
  {
    public respond_new_session() {}
    
    private uint _sessionid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sessionid
    {
      get { return _sessionid; }
      set { _sessionid = value; }
    }
    private string _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_hearbeat")]
  public partial class request_hearbeat : global::ProtoBuf.IExtensible
  {
    public request_hearbeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_hearbeat")]
  public partial class respond_hearbeat : global::ProtoBuf.IExtensible
  {
    public respond_hearbeat() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_logic_msg")]
  public partial class request_logic_msg : global::ProtoBuf.IExtensible
  {
    public request_logic_msg() {}
    
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_logic_msg")]
  public partial class respond_logic_msg : global::ProtoBuf.IExtensible
  {
    public respond_logic_msg() {}
    
    private byte[] _data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }

    private role_property _rolepro = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rolepro", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_property rolepro
    {
      get { return _rolepro; }
      set { _rolepro = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_daily_reset")]
  public partial class request_daily_reset : global::ProtoBuf.IExtensible
  {
    public request_daily_reset() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_daily_reset")]
  public partial class respond_daily_reset : global::ProtoBuf.IExtensible
  {
    public respond_daily_reset() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_random_name")]
  public partial class request_random_name : global::ProtoBuf.IExtensible
  {
    public request_random_name() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_random_name")]
  public partial class respond_random_name : global::ProtoBuf.IExtensible
  {
    public respond_random_name() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}