//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_gm.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_msg_gm")]
  public partial class request_msg_gm : global::ProtoBuf.IExtensible
  {
    public request_msg_gm() {}
    
    private string _cmd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_msg_gm")]
  public partial class respond_msg_gm : global::ProtoBuf.IExtensible
  {
    public respond_msg_gm() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _cmd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cmd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string cmd
    {
      get { return _cmd; }
      set { _cmd = value; }
    }
    private bool _rst;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rst", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool rst
    {
      get { return _rst; }
      set { _rst = value; }
    }

    private string _errmsg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"errmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errmsg
    {
      get { return _errmsg; }
      set { _errmsg = value; }
    }

    private string _param1 = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"param1", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param1
    {
      get { return _param1; }
      set { _param1 = value; }
    }

    private string _param2 = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"param2", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param2
    {
      get { return _param2; }
      set { _param2 = value; }
    }

    private string _param3 = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"param3", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param3
    {
      get { return _param3; }
      set { _param3 = value; }
    }

    private string _param4 = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"param4", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param4
    {
      get { return _param4; }
      set { _param4 = value; }
    }

    private string _param5 = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"param5", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string param5
    {
      get { return _param5; }
      set { _param5 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}