//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_activity.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_join_activity")]
  public partial class request_join_activity : global::ProtoBuf.IExtensible
  {
    public request_join_activity() {}
    
    private int _resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_join_activity")]
  public partial class respond_join_activity : global::ProtoBuf.IExtensible
  {
    public respond_join_activity() {}
    
    private uint _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }

    private int _scene_resid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"scene_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scene_resid
    {
      get { return _scene_resid; }
      set { _scene_resid = value; }
    }

    private uint _start_time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }

    private uint _over_time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"over_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint over_time
    {
      get { return _over_time; }
      set { _over_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"activity_time_info")]
  public partial class activity_time_info : global::ProtoBuf.IExtensible
  {
    public activity_time_info() {}
    
    private int _activity_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"activity_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activity_type
    {
      get { return _activity_type; }
      set { _activity_type = value; }
    }
    private int _time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_activity_info")]
  public partial class role_activity_info : global::ProtoBuf.IExtensible
  {
    public role_activity_info() {}
    
    private readonly global::System.Collections.Generic.List<activity_time_info> _timeinfo = new global::System.Collections.Generic.List<activity_time_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"timeinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<activity_time_info> timeinfo
    {
      get { return _timeinfo; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _complete_resid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"complete_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> complete_resid
    {
      get { return _complete_resid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}