//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_property.hxx
// Note: requires additional types generated from: message_guid.hxx
// Note: requires additional types generated from: message_shop.hxx
// Note: requires additional types generated from: message_scene.hxx
// Note: requires additional types generated from: message_item.hxx
// Note: requires additional types generated from: message_quest.hxx
// Note: requires additional types generated from: message_challenge_stage.hxx
// Note: requires additional types generated from: message_activity.hxx
// Note: requires additional types generated from: message_wing.hxx
// Note: requires additional types generated from: message_egg.hxx
// Note: requires additional types generated from: message_mail.hxx
// Note: requires additional types generated from: message_seven_state.hxx
// Note: requires additional types generated from: message_player_plan_stage.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"property_value_bool")]
  public partial class property_value_bool : global::ProtoBuf.IExtensible
  {
    public property_value_bool() {}
    
    private bool _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"property_value_int")]
  public partial class property_value_int : global::ProtoBuf.IExtensible
  {
    public property_value_int() {}
    
    private int _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"property_value_uint")]
  public partial class property_value_uint : global::ProtoBuf.IExtensible
  {
    public property_value_uint() {}
    
    private uint _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"property_value_ulong")]
  public partial class property_value_ulong : global::ProtoBuf.IExtensible
  {
    public property_value_ulong() {}
    
    private ulong _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"property_value_float")]
  public partial class property_value_float : global::ProtoBuf.IExtensible
  {
    public property_value_float() {}
    
    private float _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"property_value_string")]
  public partial class property_value_string : global::ProtoBuf.IExtensible
  {
    public property_value_string() {}
    
    private string _value;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_simple_info")]
  public partial class role_simple_info : global::ProtoBuf.IExtensible
  {
    public role_simple_info() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _job;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_skill_info")]
  public partial class role_skill_info : global::ProtoBuf.IExtensible
  {
    public role_skill_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _levels = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"levels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> levels
    {
      get { return _levels; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _equips = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"equips", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> equips
    {
      get { return _equips; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bap_fittings_info")]
  public partial class bap_fittings_info : global::ProtoBuf.IExtensible
  {
    public bap_fittings_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _mproperty = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mproperty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mproperty
    {
      get { return _mproperty; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _mvalue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mvalue
    {
      get { return _mvalue; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _mlock = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(3, Name=@"mlock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> mlock
    {
      get { return _mlock; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_mall_day_info")]
  public partial class role_mall_day_info : global::ProtoBuf.IExtensible
  {
    public role_mall_day_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _mallid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mallid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mallid
    {
      get { return _mallid; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _count = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> count
    {
      get { return _count; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_mall_foever_info")]
  public partial class role_mall_foever_info : global::ProtoBuf.IExtensible
  {
    public role_mall_foever_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _itemid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> itemid
    {
      get { return _itemid; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _count = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> count
    {
      get { return _count; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_bag_diff_info")]
  public partial class role_bag_diff_info : global::ProtoBuf.IExtensible
  {
    public role_bag_diff_info() {}
    
    private int _bagType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagType
    {
      get { return _bagType; }
      set { _bagType = value; }
    }
    private bag_item_info _item;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bag_item_info item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_shop_info")]
  public partial class role_shop_info : global::ProtoBuf.IExtensible
  {
    public role_shop_info() {}
    
    private readonly global::System.Collections.Generic.List<role_shop_item_info> _item = new global::System.Collections.Generic.List<role_shop_item_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<role_shop_item_info> item
    {
      get { return _item; }
    }
  
    private role_shop_refresh_seconds _sec;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sec", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public role_shop_refresh_seconds sec
    {
      get { return _sec; }
      set { _sec = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_arena")]
  public partial class role_arena : global::ProtoBuf.IExtensible
  {
    public role_arena() {}
    

    private property_value_uint _cur_rank = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cur_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint cur_rank
    {
      get { return _cur_rank; }
      set { _cur_rank = value; }
    }

    private property_value_uint _max_rank = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint max_rank
    {
      get { return _max_rank; }
      set { _max_rank = value; }
    }

    private property_value_uint _score = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint score
    {
      get { return _score; }
      set { _score = value; }
    }

    private property_value_uint _left_times = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint left_times
    {
      get { return _left_times; }
      set { _left_times = value; }
    }

    private property_value_uint _buy_times = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint buy_times
    {
      get { return _buy_times; }
      set { _buy_times = value; }
    }

    private property_value_ulong _last_time_stamp = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"last_time_stamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_ulong last_time_stamp
    {
      get { return _last_time_stamp; }
      set { _last_time_stamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_qualifying")]
  public partial class role_qualifying : global::ProtoBuf.IExtensible
  {
    public role_qualifying() {}
    

    private property_value_uint _cur_rank = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"cur_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint cur_rank
    {
      get { return _cur_rank; }
      set { _cur_rank = value; }
    }

    private property_value_uint _max_rank = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"max_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint max_rank
    {
      get { return _max_rank; }
      set { _max_rank = value; }
    }

    private property_value_uint _left_times = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"left_times", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint left_times
    {
      get { return _left_times; }
      set { _left_times = value; }
    }

    private property_value_uint _buy_times = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buy_times", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint buy_times
    {
      get { return _buy_times; }
      set { _buy_times = value; }
    }

    private property_value_ulong _last_time_stamp = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"last_time_stamp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_ulong last_time_stamp
    {
      get { return _last_time_stamp; }
      set { _last_time_stamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_egg_info")]
  public partial class role_egg_info : global::ProtoBuf.IExtensible
  {
    public role_egg_info() {}
    
    private readonly global::System.Collections.Generic.List<role_egg_item_info> _item = new global::System.Collections.Generic.List<role_egg_item_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<role_egg_item_info> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_title_info")]
  public partial class role_title_info : global::ProtoBuf.IExtensible
  {
    public role_title_info() {}
    

    private property_value_int _titleid = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"titleid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_int titleid
    {
      get { return _titleid; }
      set { _titleid = value; }
    }

    private byte[] _title_flags = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title_flags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] title_flags
    {
      get { return _title_flags; }
      set { _title_flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_fashion_item_info")]
  public partial class role_fashion_item_info : global::ProtoBuf.IExtensible
  {
    public role_fashion_item_info() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _starnum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"starnum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint starnum
    {
      get { return _starnum; }
      set { _starnum = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_fashion_info")]
  public partial class role_fashion_info : global::ProtoBuf.IExtensible
  {
    public role_fashion_info() {}
    

    private property_value_uint _unlock_count = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unlock_count", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint unlock_count
    {
      get { return _unlock_count; }
      set { _unlock_count = value; }
    }

    private property_value_int _head_id = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"head_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_int head_id
    {
      get { return _head_id; }
      set { _head_id = value; }
    }

    private property_value_int _uppper_body_id = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"uppper_body_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_int uppper_body_id
    {
      get { return _uppper_body_id; }
      set { _uppper_body_id = value; }
    }

    private property_value_int _lower_body_id = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lower_body_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_int lower_body_id
    {
      get { return _lower_body_id; }
      set { _lower_body_id = value; }
    }
    private readonly global::System.Collections.Generic.List<role_fashion_item_info> _items = new global::System.Collections.Generic.List<role_fashion_item_info>();
    [global::ProtoBuf.ProtoMember(5, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<role_fashion_item_info> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_fund_info")]
  public partial class role_fund_info : global::ProtoBuf.IExtensible
  {
    public role_fund_info() {}
    
    private int _end_seconds;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"end_seconds", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int end_seconds
    {
      get { return _end_seconds; }
      set { _end_seconds = value; }
    }

    private byte[] _fund_flags = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"fund_flags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] fund_flags
    {
      get { return _fund_flags; }
      set { _fund_flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_totalcharge_info")]
  public partial class role_totalcharge_info : global::ProtoBuf.IExtensible
  {
    public role_totalcharge_info() {}
    

    private property_value_int _totalcharge_num = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"totalcharge_num", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_int totalcharge_num
    {
      get { return _totalcharge_num; }
      set { _totalcharge_num = value; }
    }

    private byte[] _reward_flags = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward_flags", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] reward_flags
    {
      get { return _reward_flags; }
      set { _reward_flags = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"other_role_fight_property")]
  public partial class other_role_fight_property : global::ProtoBuf.IExtensible
  {
    public other_role_fight_property() {}
    
    private MSGGuild _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _job;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }
    private uint _sex;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _weapon_id;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"weapon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint weapon_id
    {
      get { return _weapon_id; }
      set { _weapon_id = value; }
    }
    private uint _sub_weapon_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"sub_weapon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint sub_weapon_id
    {
      get { return _sub_weapon_id; }
      set { _sub_weapon_id = value; }
    }
    private uint _stren_lv;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"stren_lv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint stren_lv
    {
      get { return _stren_lv; }
      set { _stren_lv = value; }
    }

    private role_skill_info _skillinfo = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"skillinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_skill_info skillinfo
    {
      get { return _skillinfo; }
      set { _skillinfo = value; }
    }
    private readonly global::System.Collections.Generic.List<bap_fittings_info> _fittingslot = new global::System.Collections.Generic.List<bap_fittings_info>();
    [global::ProtoBuf.ProtoMember(10, Name=@"fittingslot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bap_fittings_info> fittingslot
    {
      get { return _fittingslot; }
    }
  

    private msg_wing_info _wing_info = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"wing_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg_wing_info wing_info
    {
      get { return _wing_info; }
      set { _wing_info = value; }
    }

    private role_fashion_info _fashion_info = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"fashion_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_fashion_info fashion_info
    {
      get { return _fashion_info; }
      set { _fashion_info = value; }
    }

    private crop_info _maincrops = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"maincrops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public crop_info maincrops
    {
      get { return _maincrops; }
      set { _maincrops = value; }
    }

    private crop_info _subcrops = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"subcrops", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public crop_info subcrops
    {
      get { return _subcrops; }
      set { _subcrops = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_wing_item_data")]
  public partial class msg_wing_item_data : global::ProtoBuf.IExtensible
  {
    public msg_wing_item_data() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _process;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint process
    {
      get { return _process; }
      set { _process = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_wing_info")]
  public partial class msg_wing_info : global::ProtoBuf.IExtensible
  {
    public msg_wing_info() {}
    

    private property_value_uint _unlock_count = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"unlock_count", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint unlock_count
    {
      get { return _unlock_count; }
      set { _unlock_count = value; }
    }

    private property_value_int _wearid = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wearid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_int wearid
    {
      get { return _wearid; }
      set { _wearid = value; }
    }
    private readonly global::System.Collections.Generic.List<msg_wing_item_data> _items = new global::System.Collections.Generic.List<msg_wing_item_data>();
    [global::ProtoBuf.ProtoMember(3, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg_wing_item_data> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_activity_type_info")]
  public partial class role_activity_type_info : global::ProtoBuf.IExtensible
  {
    public role_activity_type_info() {}
    
    private readonly global::System.Collections.Generic.List<activity_time_info> _item = new global::System.Collections.Generic.List<activity_time_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<activity_time_info> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_activity_complete_info")]
  public partial class role_activity_complete_info : global::ProtoBuf.IExtensible
  {
    public role_activity_complete_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _act = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"act", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> act
    {
      get { return _act; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_levelup_info")]
  public partial class role_levelup_info : global::ProtoBuf.IExtensible
  {
    public role_levelup_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _levels = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"levels", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> levels
    {
      get { return _levels; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_map_info")]
  public partial class role_map_info : global::ProtoBuf.IExtensible
  {
    public role_map_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _mapid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mapid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mapid
    {
      get { return _mapid; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _unlock = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(2, Name=@"unlock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> unlock
    {
      get { return _unlock; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"zone_reward_info")]
  public partial class zone_reward_info : global::ProtoBuf.IExtensible
  {
    public zone_reward_info() {}
    
    private int _zoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private bool _mhasobtained;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mhasobtained", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool mhasobtained
    {
      get { return _mhasobtained; }
      set { _mhasobtained = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"zones_reward_info")]
  public partial class zones_reward_info : global::ProtoBuf.IExtensible
  {
    public zones_reward_info() {}
    
    private readonly global::System.Collections.Generic.List<zone_reward_info> _zones_reward = new global::System.Collections.Generic.List<zone_reward_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"zones_reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<zone_reward_info> zones_reward
    {
      get { return _zones_reward; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"crop_info")]
  public partial class crop_info : global::ProtoBuf.IExtensible
  {
    public crop_info() {}
    
    private int _cropsid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cropsid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cropsid
    {
      get { return _cropsid; }
      set { _cropsid = value; }
    }
    private int _starslv;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"starslv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int starslv
    {
      get { return _starslv; }
      set { _starslv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"crops_info")]
  public partial class crops_info : global::ProtoBuf.IExtensible
  {
    public crops_info() {}
    
    private readonly global::System.Collections.Generic.List<crop_info> _cropsinfo = new global::System.Collections.Generic.List<crop_info>();
    [global::ProtoBuf.ProtoMember(1, Name=@"cropsinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<crop_info> cropsinfo
    {
      get { return _cropsinfo; }
    }
  

    private int _main_crops_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"main_crops_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int main_crops_id
    {
      get { return _main_crops_id; }
      set { _main_crops_id = value; }
    }

    private int _sub_crops_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sub_crops_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sub_crops_id
    {
      get { return _sub_crops_id; }
      set { _sub_crops_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_property")]
  public partial class role_property : global::ProtoBuf.IExtensible
  {
    public role_property() {}
    

    private property_value_string _name = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_string name
    {
      get { return _name; }
      set { _name = value; }
    }

    private property_value_uint _resid = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint resid
    {
      get { return _resid; }
      set { _resid = value; }
    }

    private property_value_uint _sex = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private property_value_uint _level = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint level
    {
      get { return _level; }
      set { _level = value; }
    }

    private property_value_uint _vip_value = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vip_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint vip_value
    {
      get { return _vip_value; }
      set { _vip_value = value; }
    }

    private property_value_uint _vip_level = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vip_level", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint vip_level
    {
      get { return _vip_level; }
      set { _vip_level = value; }
    }

    private property_value_uint _money_game = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"money_game", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint money_game
    {
      get { return _money_game; }
      set { _money_game = value; }
    }

    private property_value_uint _money_rmb = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"money_rmb", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint money_rmb
    {
      get { return _money_rmb; }
      set { _money_rmb = value; }
    }

    private property_value_uint _money_prestige = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"money_prestige", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint money_prestige
    {
      get { return _money_prestige; }
      set { _money_prestige = value; }
    }

    private property_value_uint _money_stren = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"money_stren", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint money_stren
    {
      get { return _money_stren; }
      set { _money_stren = value; }
    }

    private property_value_uint _money_arena = null;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"money_arena", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint money_arena
    {
      get { return _money_arena; }
      set { _money_arena = value; }
    }

    private property_value_uint _weapon_id = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"weapon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint weapon_id
    {
      get { return _weapon_id; }
      set { _weapon_id = value; }
    }

    private property_value_uint _sub_weapon_id = null;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"sub_weapon_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint sub_weapon_id
    {
      get { return _sub_weapon_id; }
      set { _sub_weapon_id = value; }
    }

    private property_value_uint _exp = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }

    private property_value_uint _stren_lv = null;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"stren_lv", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint stren_lv
    {
      get { return _stren_lv; }
      set { _stren_lv = value; }
    }

    private property_value_uint _sp = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"sp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint sp
    {
      get { return _sp; }
      set { _sp = value; }
    }

    private property_value_ulong _sp_next_inc_time = null;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"sp_next_inc_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_ulong sp_next_inc_time
    {
      get { return _sp_next_inc_time; }
      set { _sp_next_inc_time = value; }
    }

    private property_value_uint _fittchance = null;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"fittchance", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint fittchance
    {
      get { return _fittchance; }
      set { _fittchance = value; }
    }

    private property_value_uint _challenge_currentfloor = null;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"challenge_currentfloor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint challenge_currentfloor
    {
      get { return _challenge_currentfloor; }
      set { _challenge_currentfloor = value; }
    }

    private property_value_uint _challenge_maxfloor = null;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"challenge_maxfloor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint challenge_maxfloor
    {
      get { return _challenge_maxfloor; }
      set { _challenge_maxfloor = value; }
    }

    private property_value_uint _challenge_weekscore = null;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"challenge_weekscore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint challenge_weekscore
    {
      get { return _challenge_weekscore; }
      set { _challenge_weekscore = value; }
    }
    private readonly global::System.Collections.Generic.List<challenge_stage_floor_info> _challengestage_floor = new global::System.Collections.Generic.List<challenge_stage_floor_info>();
    [global::ProtoBuf.ProtoMember(22, Name=@"challengestage_floor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<challenge_stage_floor_info> challengestage_floor
    {
      get { return _challengestage_floor; }
    }
  

    private role_activity_type_info _activity_time = null;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"activity_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_activity_type_info activity_time
    {
      get { return _activity_time; }
      set { _activity_time = value; }
    }

    private role_activity_complete_info _activity_complete = null;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"activity_complete", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_activity_complete_info activity_complete
    {
      get { return _activity_complete; }
      set { _activity_complete = value; }
    }

    private property_value_uint _mail_count = null;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"mail_count", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint mail_count
    {
      get { return _mail_count; }
      set { _mail_count = value; }
    }

    private bag_info _normalbag = null;
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"normalbag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bag_info normalbag
    {
      get { return _normalbag; }
      set { _normalbag = value; }
    }

    private bag_info _equipbag = null;
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"equipbag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bag_info equipbag
    {
      get { return _equipbag; }
      set { _equipbag = value; }
    }

    private bag_info _weaponbag = null;
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"weaponbag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bag_info weaponbag
    {
      get { return _weaponbag; }
      set { _weaponbag = value; }
    }

    private bag_info _gembag = null;
    [global::ProtoBuf.ProtoMember(29, IsRequired = false, Name=@"gembag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public bag_info gembag
    {
      get { return _gembag; }
      set { _gembag = value; }
    }
    private readonly global::System.Collections.Generic.List<role_bag_diff_info> _bag_diff = new global::System.Collections.Generic.List<role_bag_diff_info>();
    [global::ProtoBuf.ProtoMember(30, Name=@"bag_diff", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<role_bag_diff_info> bag_diff
    {
      get { return _bag_diff; }
    }
  

    private role_skill_info _skillinfo = null;
    [global::ProtoBuf.ProtoMember(31, IsRequired = false, Name=@"skillinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_skill_info skillinfo
    {
      get { return _skillinfo; }
      set { _skillinfo = value; }
    }

    private role_stageinfo _stageinfo = null;
    [global::ProtoBuf.ProtoMember(32, IsRequired = false, Name=@"stageinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_stageinfo stageinfo
    {
      get { return _stageinfo; }
      set { _stageinfo = value; }
    }
    private readonly global::System.Collections.Generic.List<bap_fittings_info> _fittingslot = new global::System.Collections.Generic.List<bap_fittings_info>();
    [global::ProtoBuf.ProtoMember(33, Name=@"fittingslot", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bap_fittings_info> fittingslot
    {
      get { return _fittingslot; }
    }
  

    private role_questinfo _questinfo = null;
    [global::ProtoBuf.ProtoMember(34, IsRequired = false, Name=@"questinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_questinfo questinfo
    {
      get { return _questinfo; }
      set { _questinfo = value; }
    }

    private role_mall_day_info _mall_dayinfo = null;
    [global::ProtoBuf.ProtoMember(35, IsRequired = false, Name=@"mall_dayinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_mall_day_info mall_dayinfo
    {
      get { return _mall_dayinfo; }
      set { _mall_dayinfo = value; }
    }

    private role_mall_foever_info _mall_feverinfo = null;
    [global::ProtoBuf.ProtoMember(36, IsRequired = false, Name=@"mall_feverinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_mall_foever_info mall_feverinfo
    {
      get { return _mall_feverinfo; }
      set { _mall_feverinfo = value; }
    }

    private msg_wing_info _wing_info = null;
    [global::ProtoBuf.ProtoMember(37, IsRequired = false, Name=@"wing_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg_wing_info wing_info
    {
      get { return _wing_info; }
      set { _wing_info = value; }
    }

    private role_shop_info _shop_info = null;
    [global::ProtoBuf.ProtoMember(38, IsRequired = false, Name=@"shop_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_shop_info shop_info
    {
      get { return _shop_info; }
      set { _shop_info = value; }
    }

    private role_arena _arenainfo = null;
    [global::ProtoBuf.ProtoMember(39, IsRequired = false, Name=@"arenainfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_arena arenainfo
    {
      get { return _arenainfo; }
      set { _arenainfo = value; }
    }

    private role_qualifying _qualifying_info = null;
    [global::ProtoBuf.ProtoMember(40, IsRequired = false, Name=@"qualifying_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_qualifying qualifying_info
    {
      get { return _qualifying_info; }
      set { _qualifying_info = value; }
    }

    private property_value_string _next_daily_resettime = null;
    [global::ProtoBuf.ProtoMember(41, IsRequired = false, Name=@"next_daily_resettime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_string next_daily_resettime
    {
      get { return _next_daily_resettime; }
      set { _next_daily_resettime = value; }
    }

    private role_levelup_info _levelup_info = null;
    [global::ProtoBuf.ProtoMember(42, IsRequired = false, Name=@"levelup_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_levelup_info levelup_info
    {
      get { return _levelup_info; }
      set { _levelup_info = value; }
    }

    private role_egg_info _egg_info = null;
    [global::ProtoBuf.ProtoMember(43, IsRequired = false, Name=@"egg_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_egg_info egg_info
    {
      get { return _egg_info; }
      set { _egg_info = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _grades = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(44, Name=@"grades", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> grades
    {
      get { return _grades; }
    }
  

    private property_value_uint _rmb_used = null;
    [global::ProtoBuf.ProtoMember(45, IsRequired = false, Name=@"rmb_used", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint rmb_used
    {
      get { return _rmb_used; }
      set { _rmb_used = value; }
    }

    private property_value_int _last_city_id = null;
    [global::ProtoBuf.ProtoMember(46, IsRequired = false, Name=@"last_city_id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_int last_city_id
    {
      get { return _last_city_id; }
      set { _last_city_id = value; }
    }

    private role_map_info _map_info = null;
    [global::ProtoBuf.ProtoMember(47, IsRequired = false, Name=@"map_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_map_info map_info
    {
      get { return _map_info; }
      set { _map_info = value; }
    }

    private zones_reward_info _zones_reward_info = null;
    [global::ProtoBuf.ProtoMember(49, IsRequired = false, Name=@"zones_reward_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public zones_reward_info zones_reward_info
    {
      get { return _zones_reward_info; }
      set { _zones_reward_info = value; }
    }

    private role_title_info _title_info = null;
    [global::ProtoBuf.ProtoMember(50, IsRequired = false, Name=@"title_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_title_info title_info
    {
      get { return _title_info; }
      set { _title_info = value; }
    }

    private uint _lasterror = default(uint);
    [global::ProtoBuf.ProtoMember(51, IsRequired = false, Name=@"lasterror", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lasterror
    {
      get { return _lasterror; }
      set { _lasterror = value; }
    }

    private crops_info _cropsinfo = null;
    [global::ProtoBuf.ProtoMember(52, IsRequired = false, Name=@"cropsinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public crops_info cropsinfo
    {
      get { return _cropsinfo; }
      set { _cropsinfo = value; }
    }

    private role_fund_info _fund_info = null;
    [global::ProtoBuf.ProtoMember(53, IsRequired = false, Name=@"fund_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_fund_info fund_info
    {
      get { return _fund_info; }
      set { _fund_info = value; }
    }

    private role_fashion_info _fashion_info = null;
    [global::ProtoBuf.ProtoMember(54, IsRequired = false, Name=@"fashion_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_fashion_info fashion_info
    {
      get { return _fashion_info; }
      set { _fashion_info = value; }
    }
    private readonly global::System.Collections.Generic.List<respond_seven_state> _statenfo = new global::System.Collections.Generic.List<respond_seven_state>();
    [global::ProtoBuf.ProtoMember(55, Name=@"statenfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<respond_seven_state> statenfo
    {
      get { return _statenfo; }
    }
  

    private property_value_bool _weaponskill = null;
    [global::ProtoBuf.ProtoMember(56, IsRequired = false, Name=@"weaponskill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_bool weaponskill
    {
      get { return _weaponskill; }
      set { _weaponskill = value; }
    }

    private property_value_bool _firstcharge_picked = null;
    [global::ProtoBuf.ProtoMember(57, IsRequired = false, Name=@"firstcharge_picked", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_bool firstcharge_picked
    {
      get { return _firstcharge_picked; }
      set { _firstcharge_picked = value; }
    }

    private property_value_bool _charged = null;
    [global::ProtoBuf.ProtoMember(58, IsRequired = false, Name=@"charged", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_bool charged
    {
      get { return _charged; }
      set { _charged = value; }
    }

    private property_value_uint _mail_unread_count = null;
    [global::ProtoBuf.ProtoMember(59, IsRequired = false, Name=@"mail_unread_count", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint mail_unread_count
    {
      get { return _mail_unread_count; }
      set { _mail_unread_count = value; }
    }
    private readonly global::System.Collections.Generic.List<respond_player_plan_report> _planinfo = new global::System.Collections.Generic.List<respond_player_plan_report>();
    [global::ProtoBuf.ProtoMember(60, Name=@"planinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<respond_player_plan_report> planinfo
    {
      get { return _planinfo; }
    }
  

    private role_totalcharge_info _totalcharge_info = null;
    [global::ProtoBuf.ProtoMember(61, IsRequired = false, Name=@"totalcharge_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_totalcharge_info totalcharge_info
    {
      get { return _totalcharge_info; }
      set { _totalcharge_info = value; }
    }

    private property_value_uint _charge_rewards = null;
    [global::ProtoBuf.ProtoMember(62, IsRequired = false, Name=@"charge_rewards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint charge_rewards
    {
      get { return _charge_rewards; }
      set { _charge_rewards = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"WING_STATE")]
    public enum WING_STATE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LOCKED", Value=0)]
      LOCKED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UNLOCKED", Value=1)]
      UNLOCKED = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"WEAR", Value=2)]
      WEAR = 2
    }
  
}