//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_title.hxx
// Note: requires additional types generated from: message_guid.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_title_item_info")]
  public partial class role_title_item_info : global::ProtoBuf.IExtensible
  {
    public role_title_item_info() {}
    
    private readonly global::System.Collections.Generic.List<int> _titleid = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"titleid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> titleid
    {
      get { return _titleid; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_title_op")]
  public partial class request_title_op : global::ProtoBuf.IExtensible
  {
    public request_title_op() {}
    
    private int _op_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private int _title_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"title_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int title_id
    {
      get { return _title_id; }
      set { _title_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_title_op")]
  public partial class respond_title_op : global::ProtoBuf.IExtensible
  {
    public respond_title_op() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _op_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private int _title_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"title_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int title_id
    {
      get { return _title_id; }
      set { _title_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"TITLE_OP_TYPE")]
    public enum TITLE_OP_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"TITLE_GET", Value=1)]
      TITLE_GET = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TITLE_LOSE", Value=2)]
      TITLE_LOSE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TITLE_PICK_UP", Value=3)]
      TITLE_PICK_UP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"TITLE_PICK_OFF", Value=4)]
      TITLE_PICK_OFF = 4
    }
  
}