//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_item.hxx
// Note: requires additional types generated from: message_guid.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item_base_info")]
  public partial class item_base_info : global::ProtoBuf.IExtensible
  {
    public item_base_info() {}
    
    private MSGGuild _itemguid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemguid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild itemguid
    {
      get { return _itemguid; }
      set { _itemguid = value; }
    }
    private int _resid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private uint _createtime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"createtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint createtime
    {
      get { return _createtime; }
      set { _createtime = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"weapon_item_info")]
  public partial class weapon_item_info : global::ProtoBuf.IExtensible
  {
    public weapon_item_info() {}
    
    private int _promotelv;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"promotelv", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int promotelv
    {
      get { return _promotelv; }
      set { _promotelv = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"normal_item_info")]
  public partial class normal_item_info : global::ProtoBuf.IExtensible
  {
    public normal_item_info() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"stone_info")]
  public partial class stone_info : global::ProtoBuf.IExtensible
  {
    public stone_info() {}
    
    private int _stoneid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"stoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stoneid
    {
      get { return _stoneid; }
      set { _stoneid = value; }
    }
    private int _stonepos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stonepos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stonepos
    {
      get { return _stonepos; }
      set { _stonepos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"equip_item_info")]
  public partial class equip_item_info : global::ProtoBuf.IExtensible
  {
    public equip_item_info() {}
    
    private int _strenlevel;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"strenlevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int strenlevel
    {
      get { return _strenlevel; }
      set { _strenlevel = value; }
    }
    private int _starslevel;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"starslevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int starslevel
    {
      get { return _starslevel; }
      set { _starslevel = value; }
    }
    private readonly global::System.Collections.Generic.List<stone_info> _stoneinlays = new global::System.Collections.Generic.List<stone_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"stoneinlays", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<stone_info> stoneinlays
    {
      get { return _stoneinlays; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item_info")]
  public partial class item_info : global::ProtoBuf.IExtensible
  {
    public item_info() {}
    
    private int _itemtype;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemtype
    {
      get { return _itemtype; }
      set { _itemtype = value; }
    }

    private item_base_info _baseinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"baseinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public item_base_info baseinfo
    {
      get { return _baseinfo; }
      set { _baseinfo = value; }
    }

    private weapon_item_info _weapon_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"weapon_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public weapon_item_info weapon_info
    {
      get { return _weapon_info; }
      set { _weapon_info = value; }
    }

    private normal_item_info _normal_info = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"normal_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public normal_item_info normal_info
    {
      get { return _normal_info; }
      set { _normal_info = value; }
    }

    private equip_item_info _equip_info = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"equip_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public equip_item_info equip_info
    {
      get { return _equip_info; }
      set { _equip_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bag_item_info")]
  public partial class bag_item_info : global::ProtoBuf.IExtensible
  {
    public bag_item_info() {}
    
    private int _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }

    private item_info _item = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public item_info item
    {
      get { return _item; }
      set { _item = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bag_info")]
  public partial class bag_info : global::ProtoBuf.IExtensible
  {
    public bag_info() {}
    
    private int _max_size;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"max_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_size
    {
      get { return _max_size; }
      set { _max_size = value; }
    }
    private int _max_valid_size;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"max_valid_size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_valid_size
    {
      get { return _max_valid_size; }
      set { _max_valid_size = value; }
    }
    private readonly global::System.Collections.Generic.List<bag_item_info> _items = new global::System.Collections.Generic.List<bag_item_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bag_item_info> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"award_item_info")]
  public partial class award_item_info : global::ProtoBuf.IExtensible
  {
    public award_item_info() {}
    
    private int _resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item_sale_request")]
  public partial class item_sale_request : global::ProtoBuf.IExtensible
  {
    public item_sale_request() {}
    
    private int _itemid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemid
    {
      get { return _itemid; }
      set { _itemid = value; }
    }
    private int _itemcount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"itemcount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemcount
    {
      get { return _itemcount; }
      set { _itemcount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item_sale_respond")]
  public partial class item_sale_respond : global::ProtoBuf.IExtensible
  {
    public item_sale_respond() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }

    private int _salemoney = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"salemoney", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int salemoney
    {
      get { return _salemoney; }
      set { _salemoney = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"box_item_request")]
  public partial class box_item_request : global::ProtoBuf.IExtensible
  {
    public box_item_request() {}
    
    private int _op_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }

    private int _bagtype = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"bagtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bagtype
    {
      get { return _bagtype; }
      set { _bagtype = value; }
    }

    private int _bagpos = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bagpos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bagpos
    {
      get { return _bagpos; }
      set { _bagpos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"box_item_respond")]
  public partial class box_item_respond : global::ProtoBuf.IExtensible
  {
    public box_item_respond() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private readonly global::System.Collections.Generic.List<award_item_info> _award_items = new global::System.Collections.Generic.List<award_item_info>();
    [global::ProtoBuf.ProtoMember(2, Name=@"award_items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<award_item_info> award_items
    {
      get { return _award_items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BOX_ITEM_OP_TYPE")]
    public enum BOX_ITEM_OP_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OP_TYPE_OPEN", Value=1)]
      OP_TYPE_OPEN = 1
    }
  
}