//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_seven_state.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_seven_state")]
  public partial class request_seven_state : global::ProtoBuf.IExtensible
  {
    public request_seven_state() {}
    
    private int _week;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"week", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int week
    {
      get { return _week; }
      set { _week = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_seven_state")]
  public partial class respond_seven_state : global::ProtoBuf.IExtensible
  {
    public respond_seven_state() {}
    
    private int _week;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"week", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int week
    {
      get { return _week; }
      set { _week = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}