//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_yazhixiee.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_yazhixiee_report")]
  public partial class request_yazhixiee_report : global::ProtoBuf.IExtensible
  {
    public request_yazhixiee_report() {}
    
    private uint _score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _time_cost;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time_cost
    {
      get { return _time_cost; }
      set { _time_cost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"yazhixiee_ranklist_role_info")]
  public partial class yazhixiee_ranklist_role_info : global::ProtoBuf.IExtensible
  {
    public yazhixiee_ranklist_role_info() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_yazhixiee_report")]
  public partial class respond_yazhixiee_report : global::ProtoBuf.IExtensible
  {
    public respond_yazhixiee_report() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private readonly global::System.Collections.Generic.List<yazhixiee_ranklist_role_info> _sortinfo = new global::System.Collections.Generic.List<yazhixiee_ranklist_role_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"sortinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<yazhixiee_ranklist_role_info> sortinfo
    {
      get { return _sortinfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_yazhixiee_over")]
  public partial class request_yazhixiee_over : global::ProtoBuf.IExtensible
  {
    public request_yazhixiee_over() {}
    
    private uint _score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _time_cost;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"time_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time_cost
    {
      get { return _time_cost; }
      set { _time_cost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_yazhixiee_over")]
  public partial class respond_yazhixiee_over : global::ProtoBuf.IExtensible
  {
    public respond_yazhixiee_over() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _time_cost;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint time_cost
    {
      get { return _time_cost; }
      set { _time_cost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}