//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_arena.hxx
// Note: requires additional types generated from: message_guid.hxx
// Note: requires additional types generated from: message_property.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_arena_record")]
  public partial class msg_arena_record : global::ProtoBuf.IExtensible
  {
    public msg_arena_record() {}
    
    private string _src_name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"src_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string src_name
    {
      get { return _src_name; }
      set { _src_name = value; }
    }
    private string _tar_name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"tar_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tar_name
    {
      get { return _tar_name; }
      set { _tar_name = value; }
    }
    private int _src_level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"src_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int src_level
    {
      get { return _src_level; }
      set { _src_level = value; }
    }
    private int _tar_level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"tar_level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tar_level
    {
      get { return _tar_level; }
      set { _tar_level = value; }
    }
    private int _src_job;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"src_job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int src_job
    {
      get { return _src_job; }
      set { _src_job = value; }
    }
    private int _tar_job;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"tar_job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tar_job
    {
      get { return _tar_job; }
      set { _tar_job = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private ulong _time_stamp;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"time_stamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong time_stamp
    {
      get { return _time_stamp; }
      set { _time_stamp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_arena_simple_role")]
  public partial class msg_arena_simple_role : global::ProtoBuf.IExtensible
  {
    public msg_arena_simple_role() {}
    
    private MSGGuild _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _job;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"job", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint job
    {
      get { return _job; }
      set { _job = value; }
    }

    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }

    private uint _grade = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint grade
    {
      get { return _grade; }
      set { _grade = value; }
    }
    private uint _weapon_id;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"weapon_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint weapon_id
    {
      get { return _weapon_id; }
      set { _weapon_id = value; }
    }
    private uint _rank;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_msg_arena_record")]
  public partial class request_msg_arena_record : global::ProtoBuf.IExtensible
  {
    public request_msg_arena_record() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_msg_arena_record")]
  public partial class respond_msg_arena_record : global::ProtoBuf.IExtensible
  {
    public respond_msg_arena_record() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private readonly global::System.Collections.Generic.List<msg_arena_record> _record = new global::System.Collections.Generic.List<msg_arena_record>();
    [global::ProtoBuf.ProtoMember(2, Name=@"record", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg_arena_record> record
    {
      get { return _record; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_msg_arena_refresh")]
  public partial class request_msg_arena_refresh : global::ProtoBuf.IExtensible
  {
    public request_msg_arena_refresh() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_msg_arena_refresh")]
  public partial class respond_msg_arena_refresh : global::ProtoBuf.IExtensible
  {
    public respond_msg_arena_refresh() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private property_value_uint _cur_rank = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"cur_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public property_value_uint cur_rank
    {
      get { return _cur_rank; }
      set { _cur_rank = value; }
    }
    private readonly global::System.Collections.Generic.List<msg_arena_simple_role> _simpleroles = new global::System.Collections.Generic.List<msg_arena_simple_role>();
    [global::ProtoBuf.ProtoMember(3, Name=@"simpleroles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg_arena_simple_role> simpleroles
    {
      get { return _simpleroles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_msg_arena_begin")]
  public partial class request_msg_arena_begin : global::ProtoBuf.IExtensible
  {
    public request_msg_arena_begin() {}
    
    private MSGGuild _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_msg_arena_begin")]
  public partial class respond_msg_arena_begin : global::ProtoBuf.IExtensible
  {
    public respond_msg_arena_begin() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private other_role_fight_property _property = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"property", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public other_role_fight_property property
    {
      get { return _property; }
      set { _property = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_msg_arena_end")]
  public partial class request_msg_arena_end : global::ProtoBuf.IExtensible
  {
    public request_msg_arena_end() {}
    
    private MSGGuild _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_msg_arena_end")]
  public partial class respond_msg_arena_end : global::ProtoBuf.IExtensible
  {
    public respond_msg_arena_end() {}
    

    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private int _score = (int)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }

    private int _money = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int money
    {
      get { return _money; }
      set { _money = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_msg_arena_buy_times")]
  public partial class request_msg_arena_buy_times : global::ProtoBuf.IExtensible
  {
    public request_msg_arena_buy_times() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_msg_arena_buy_times")]
  public partial class respond_msg_arena_buy_times : global::ProtoBuf.IExtensible
  {
    public respond_msg_arena_buy_times() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}