//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_crops.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_crops_buy")]
  public partial class request_crops_buy : global::ProtoBuf.IExtensible
  {
    public request_crops_buy() {}
    
    private int _resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_crops_buy")]
  public partial class respond_crops_buy : global::ProtoBuf.IExtensible
  {
    public respond_crops_buy() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_change_crops")]
  public partial class request_change_crops : global::ProtoBuf.IExtensible
  {
    public request_change_crops() {}
    
    private int _main_crops_resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"main_crops_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int main_crops_resid
    {
      get { return _main_crops_resid; }
      set { _main_crops_resid = value; }
    }
    private int _sub_crops_resid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sub_crops_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sub_crops_resid
    {
      get { return _sub_crops_resid; }
      set { _sub_crops_resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_change_crops")]
  public partial class respond_change_crops : global::ProtoBuf.IExtensible
  {
    public respond_change_crops() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_crops_level")]
  public partial class request_crops_level : global::ProtoBuf.IExtensible
  {
    public request_crops_level() {}
    
    private int _resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_crops_level")]
  public partial class respond_crops_level : global::ProtoBuf.IExtensible
  {
    public respond_crops_level() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}