//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_player_plan_stage.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_player_plan_report")]
  public partial class request_player_plan_report : global::ProtoBuf.IExtensible
  {
    public request_player_plan_report() {}
    
    private int _planid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int planid
    {
      get { return _planid; }
      set { _planid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_player_plan_report")]
  public partial class respond_player_plan_report : global::ProtoBuf.IExtensible
  {
    public respond_player_plan_report() {}
    
    private int _planid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"planid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int planid
    {
      get { return _planid; }
      set { _planid = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private uint _jewel;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"jewel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint jewel
    {
      get { return _jewel; }
      set { _jewel = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}