//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_mall.hxx
// Note: requires additional types generated from: message_guid.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_mall_buy")]
  public partial class request_mall_buy : global::ProtoBuf.IExtensible
  {
    public request_mall_buy() {}
    
    private int _mallid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mallid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mallid
    {
      get { return _mallid; }
      set { _mallid = value; }
    }
    private int _subid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"subid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int subid
    {
      get { return _subid; }
      set { _subid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_mall_buy")]
  public partial class respond_mall_buy : global::ProtoBuf.IExtensible
  {
    public respond_mall_buy() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private int _mallid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mallid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int mallid
    {
      get { return _mallid; }
      set { _mallid = value; }
    }

    private int _subid = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"subid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int subid
    {
      get { return _subid; }
      set { _subid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}