//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_ranking.hxx
// Note: requires additional types generated from: message_guid.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ranking_player_info")]
  public partial class ranking_player_info : global::ProtoBuf.IExtensible
  {
    public ranking_player_info() {}
    
    private MSGGuild _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _rank;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rank
    {
      get { return _rank; }
      set { _rank = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _grade;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"grade", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int grade
    {
      get { return _grade; }
      set { _grade = value; }
    }

    private uint _arena_score = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"arena_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint arena_score
    {
      get { return _arena_score; }
      set { _arena_score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_ranking_list")]
  public partial class request_ranking_list : global::ProtoBuf.IExtensible
  {
    public request_ranking_list() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_ranking_list")]
  public partial class respond_ranking_list : global::ProtoBuf.IExtensible
  {
    public respond_ranking_list() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private readonly global::System.Collections.Generic.List<ranking_player_info> _level_ranking = new global::System.Collections.Generic.List<ranking_player_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"level_ranking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ranking_player_info> level_ranking
    {
      get { return _level_ranking; }
    }
  
    private readonly global::System.Collections.Generic.List<ranking_player_info> _grade_ranking = new global::System.Collections.Generic.List<ranking_player_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"grade_ranking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ranking_player_info> grade_ranking
    {
      get { return _grade_ranking; }
    }
  
    private readonly global::System.Collections.Generic.List<ranking_player_info> _arena_ranking = new global::System.Collections.Generic.List<ranking_player_info>();
    [global::ProtoBuf.ProtoMember(5, Name=@"arena_ranking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ranking_player_info> arena_ranking
    {
      get { return _arena_ranking; }
    }
  
    private readonly global::System.Collections.Generic.List<ranking_player_info> _qualifying_ranking = new global::System.Collections.Generic.List<ranking_player_info>();
    [global::ProtoBuf.ProtoMember(6, Name=@"qualifying_ranking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ranking_player_info> qualifying_ranking
    {
      get { return _qualifying_ranking; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ranking_challenge_info")]
  public partial class ranking_challenge_info : global::ProtoBuf.IExtensible
  {
    public ranking_challenge_info() {}
    
    private MSGGuild _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _challenge_weekscore;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"challenge_weekscore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint challenge_weekscore
    {
      get { return _challenge_weekscore; }
      set { _challenge_weekscore = value; }
    }
    private uint _floor;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private int _resid;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_challenge_ranking_list")]
  public partial class request_challenge_ranking_list : global::ProtoBuf.IExtensible
  {
    public request_challenge_ranking_list() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private ulong _guid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_challenge_ranking_list")]
  public partial class respond_challenge_ranking_list : global::ProtoBuf.IExtensible
  {
    public respond_challenge_ranking_list() {}
    
    private int _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }

    private uint _rankindex = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"rankindex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint rankindex
    {
      get { return _rankindex; }
      set { _rankindex = value; }
    }
    private readonly global::System.Collections.Generic.List<ranking_challenge_info> _challenge_ranking = new global::System.Collections.Generic.List<ranking_challenge_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"challenge_ranking", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ranking_challenge_info> challenge_ranking
    {
      get { return _challenge_ranking; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}