//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_quest.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_quest_award_item")]
  public partial class msg_quest_award_item : global::ProtoBuf.IExtensible
  {
    public msg_quest_award_item() {}
    
    private int _award_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"award_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int award_id
    {
      get { return _award_id; }
      set { _award_id = value; }
    }
    private uint _award_count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"award_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint award_count
    {
      get { return _award_count; }
      set { _award_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"msg_quest_award")]
  public partial class msg_quest_award : global::ProtoBuf.IExtensible
  {
    public msg_quest_award() {}
    
    private readonly global::System.Collections.Generic.List<msg_quest_award_item> _award_item = new global::System.Collections.Generic.List<msg_quest_award_item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"award_item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<msg_quest_award_item> award_item
    {
      get { return _award_item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_accept_quest")]
  public partial class request_accept_quest : global::ProtoBuf.IExtensible
  {
    public request_accept_quest() {}
    
    private int _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_accept_quest")]
  public partial class respond_accept_quest : global::ProtoBuf.IExtensible
  {
    public respond_accept_quest() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_finish_quest")]
  public partial class request_finish_quest : global::ProtoBuf.IExtensible
  {
    public request_finish_quest() {}
    
    private int _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_finish_quest")]
  public partial class respond_finish_quest : global::ProtoBuf.IExtensible
  {
    public respond_finish_quest() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }

    private msg_quest_award _awards = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"awards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public msg_quest_award awards
    {
      get { return _awards; }
      set { _awards = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_quest")]
  public partial class role_quest : global::ProtoBuf.IExtensible
  {
    public role_quest() {}
    
    private int _questid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"questid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questid
    {
      get { return _questid; }
      set { _questid = value; }
    }
    private int _questype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"questype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int questype
    {
      get { return _questype; }
      set { _questype = value; }
    }
    private int _process;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"process", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int process
    {
      get { return _process; }
      set { _process = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_questinfo")]
  public partial class role_questinfo : global::ProtoBuf.IExtensible
  {
    public role_questinfo() {}
    
    private readonly global::System.Collections.Generic.List<role_quest> _quests = new global::System.Collections.Generic.List<role_quest>();
    [global::ProtoBuf.ProtoMember(1, Name=@"quests", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<role_quest> quests
    {
      get { return _quests; }
    }
  

    private byte[] _quest_flag = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"quest_flag", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] quest_flag
    {
      get { return _quest_flag; }
      set { _quest_flag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}