//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_equip.hxx
// Note: requires additional types generated from: message_guid.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item_equip_request")]
  public partial class item_equip_request : global::ProtoBuf.IExtensible
  {
    public item_equip_request() {}
    
    private bool _isequip;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"isequip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isequip
    {
      get { return _isequip; }
      set { _isequip = value; }
    }
    private int _bagType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagType
    {
      get { return _bagType; }
      set { _bagType = value; }
    }
    private int _bagPos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bagPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagPos
    {
      get { return _bagPos; }
      set { _bagPos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"item_equip_respond")]
  public partial class item_equip_respond : global::ProtoBuf.IExtensible
  {
    public item_equip_respond() {}
    
    private uint _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bag_op_request")]
  public partial class bag_op_request : global::ProtoBuf.IExtensible
  {
    public bag_op_request() {}
    
    private int _op_type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private int _bagType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagType
    {
      get { return _bagType; }
      set { _bagType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"bag_op_respond")]
  public partial class bag_op_respond : global::ProtoBuf.IExtensible
  {
    public bag_op_respond() {}
    
    private uint _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private int _op_type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"op_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int op_type
    {
      get { return _op_type; }
      set { _op_type = value; }
    }
    private int _bagType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bagType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bagType
    {
      get { return _bagType; }
      set { _bagType = value; }
    }

    private int _vaild_number = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vaild_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vaild_number
    {
      get { return _vaild_number; }
      set { _vaild_number = value; }
    }

    private int _max_number = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"max_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int max_number
    {
      get { return _max_number; }
      set { _max_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"BAG_OP_TYPE")]
    public enum BAG_OP_TYPE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"BAG_OP_TYPE_UNLOCK", Value=0)]
      BAG_OP_TYPE_UNLOCK = 0
    }
  
}