//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_zhaocaimao.hxx
// Note: requires additional types generated from: message_property.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_zhaocaimao_report")]
  public partial class request_zhaocaimao_report : global::ProtoBuf.IExtensible
  {
    public request_zhaocaimao_report() {}
    
    private int _damage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"zhaocaimao_ranklist_role_info")]
  public partial class zhaocaimao_ranklist_role_info : global::ProtoBuf.IExtensible
  {
    public zhaocaimao_ranklist_role_info() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_zhaocaimao_report")]
  public partial class respond_zhaocaimao_report : global::ProtoBuf.IExtensible
  {
    public respond_zhaocaimao_report() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private readonly global::System.Collections.Generic.List<zhaocaimao_ranklist_role_info> _sortinfo = new global::System.Collections.Generic.List<zhaocaimao_ranklist_role_info>();
    [global::ProtoBuf.ProtoMember(3, Name=@"sortinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<zhaocaimao_ranklist_role_info> sortinfo
    {
      get { return _sortinfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_zhaocaimao_over")]
  public partial class request_zhaocaimao_over : global::ProtoBuf.IExtensible
  {
    public request_zhaocaimao_over() {}
    
    private int _damage;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_zhaocaimao_over")]
  public partial class respond_zhaocaimao_over : global::ProtoBuf.IExtensible
  {
    public respond_zhaocaimao_over() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private int _damage;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_zhaocaimao_partner")]
  public partial class request_zhaocaimao_partner : global::ProtoBuf.IExtensible
  {
    public request_zhaocaimao_partner() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_zhaocaimao_partner")]
  public partial class respond_zhaocaimao_partner : global::ProtoBuf.IExtensible
  {
    public respond_zhaocaimao_partner() {}
    
    private readonly global::System.Collections.Generic.List<other_role_fight_property> _simpleroles = new global::System.Collections.Generic.List<other_role_fight_property>();
    [global::ProtoBuf.ProtoMember(1, Name=@"simpleroles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<other_role_fight_property> simpleroles
    {
      get { return _simpleroles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_zhaocaimao_ranking")]
  public partial class request_zhaocaimao_ranking : global::ProtoBuf.IExtensible
  {
    public request_zhaocaimao_ranking() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_zhaocaimao_ranking")]
  public partial class respond_zhaocaimao_ranking : global::ProtoBuf.IExtensible
  {
    public respond_zhaocaimao_ranking() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private uint _ranking;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ranking", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ranking
    {
      get { return _ranking; }
      set { _ranking = value; }
    }
    private int _item_id;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"item_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int item_id
    {
      get { return _item_id; }
      set { _item_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}