//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_defence_depot.hxx
// Note: requires additional types generated from: message_item.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_defence_stren")]
  public partial class request_defence_stren : global::ProtoBuf.IExtensible
  {
    public request_defence_stren() {}
    
    private int _defenceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenceId
    {
      get { return _defenceId; }
      set { _defenceId = value; }
    }
    private int _packtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packtype
    {
      get { return _packtype; }
      set { _packtype = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }

    private bool _isstrenten = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isstrenten", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isstrenten
    {
      get { return _isstrenten; }
      set { _isstrenten = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_defence_stren")]
  public partial class respond_defence_stren : global::ProtoBuf.IExtensible
  {
    public respond_defence_stren() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }

    private int _errorstren = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorstren", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorstren
    {
      get { return _errorstren; }
      set { _errorstren = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_rising_stars")]
  public partial class request_rising_stars : global::ProtoBuf.IExtensible
  {
    public request_rising_stars() {}
    
    private int _defenceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenceId
    {
      get { return _defenceId; }
      set { _defenceId = value; }
    }
    private int _packtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packtype
    {
      get { return _packtype; }
      set { _packtype = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }

    private bool _isstarsten = default(bool);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"isstarsten", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isstarsten
    {
      get { return _isstarsten; }
      set { _isstarsten = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_rising_stars")]
  public partial class respond_rising_stars : global::ProtoBuf.IExtensible
  {
    public respond_rising_stars() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }

    private int _errorstars = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"errorstars", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorstars
    {
      get { return _errorstars; }
      set { _errorstars = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_defence_promote")]
  public partial class request_defence_promote : global::ProtoBuf.IExtensible
  {
    public request_defence_promote() {}
    
    private int _defenceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenceId
    {
      get { return _defenceId; }
      set { _defenceId = value; }
    }
    private int _packtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packtype
    {
      get { return _packtype; }
      set { _packtype = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_defence_promote")]
  public partial class respond_defence_promote : global::ProtoBuf.IExtensible
  {
    public respond_defence_promote() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_stone_inlay")]
  public partial class request_stone_inlay : global::ProtoBuf.IExtensible
  {
    public request_stone_inlay() {}
    
    private int _defenceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenceId
    {
      get { return _defenceId; }
      set { _defenceId = value; }
    }
    private int _stoneId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stoneId
    {
      get { return _stoneId; }
      set { _stoneId = value; }
    }
    private int _packtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"packtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packtype
    {
      get { return _packtype; }
      set { _packtype = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _stonepos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"stonepos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stonepos
    {
      get { return _stonepos; }
      set { _stonepos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_stone_inlay")]
  public partial class respond_stone_inlay : global::ProtoBuf.IExtensible
  {
    public respond_stone_inlay() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_stone_comb")]
  public partial class request_stone_comb : global::ProtoBuf.IExtensible
  {
    public request_stone_comb() {}
    
    private int _defenceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenceId
    {
      get { return _defenceId; }
      set { _defenceId = value; }
    }
    private int _stoneId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stoneId
    {
      get { return _stoneId; }
      set { _stoneId = value; }
    }
    private int _packtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"packtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packtype
    {
      get { return _packtype; }
      set { _packtype = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _stonepos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"stonepos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stonepos
    {
      get { return _stonepos; }
      set { _stonepos = value; }
    }

    private bool _isequiped = default(bool);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"isequiped", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isequiped
    {
      get { return _isequiped; }
      set { _isequiped = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_stone_comb")]
  public partial class respond_stone_comb : global::ProtoBuf.IExtensible
  {
    public respond_stone_comb() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_stone_uninlay")]
  public partial class request_stone_uninlay : global::ProtoBuf.IExtensible
  {
    public request_stone_uninlay() {}
    
    private int _defenceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenceId
    {
      get { return _defenceId; }
      set { _defenceId = value; }
    }
    private int _stoneId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stoneId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stoneId
    {
      get { return _stoneId; }
      set { _stoneId = value; }
    }
    private int _packtype;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"packtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packtype
    {
      get { return _packtype; }
      set { _packtype = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private int _stonepos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"stonepos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int stonepos
    {
      get { return _stonepos; }
      set { _stonepos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_stone_uninlay")]
  public partial class respond_stone_uninlay : global::ProtoBuf.IExtensible
  {
    public respond_stone_uninlay() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_defence_sale")]
  public partial class request_defence_sale : global::ProtoBuf.IExtensible
  {
    public request_defence_sale() {}
    
    private int _defenceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"defenceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int defenceId
    {
      get { return _defenceId; }
      set { _defenceId = value; }
    }
    private int _packtype;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"packtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int packtype
    {
      get { return _packtype; }
      set { _packtype = value; }
    }
    private int _pos;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_defence_sale")]
  public partial class respond_defence_sale : global::ProtoBuf.IExtensible
  {
    public respond_defence_sale() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }

    private int _moneysaled = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"moneysaled", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int moneysaled
    {
      get { return _moneysaled; }
      set { _moneysaled = value; }
    }

    private int _starssaled = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"starssaled", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starssaled
    {
      get { return _starssaled; }
      set { _starssaled = value; }
    }

    private int _stonesaled = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stonesaled", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stonesaled
    {
      get { return _stonesaled; }
      set { _stonesaled = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}