//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_mail.hxx
// Note: requires additional types generated from: message_guid.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_mail_s")]
  public partial class role_mail_s : global::ProtoBuf.IExtensible
  {
    public role_mail_s() {}
    

    private string _sendname = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sendname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sendname
    {
      get { return _sendname; }
      set { _sendname = value; }
    }

    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }

    private string _content = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }

    private uint _state = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint state
    {
      get { return _state; }
      set { _state = value; }
    }

    private uint _itemcnt = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"itemcnt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint itemcnt
    {
      get { return _itemcnt; }
      set { _itemcnt = value; }
    }

    private mail_item_list _itemlist = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemlist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public mail_item_list itemlist
    {
      get { return _itemlist; }
      set { _itemlist = value; }
    }

    private ulong _start_time = default(ulong);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"start_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong start_time
    {
      get { return _start_time; }
      set { _start_time = value; }
    }

    private MSGGuild _mailid = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mailid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public MSGGuild mailid
    {
      get { return _mailid; }
      set { _mailid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"player_mail_list")]
  public partial class player_mail_list : global::ProtoBuf.IExtensible
  {
    public player_mail_list() {}
    
    private readonly global::System.Collections.Generic.List<role_mail_s> _MailList = new global::System.Collections.Generic.List<role_mail_s>();
    [global::ProtoBuf.ProtoMember(1, Name=@"MailList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<role_mail_s> MailList
    {
      get { return _MailList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"mail_item")]
  public partial class mail_item : global::ProtoBuf.IExtensible
  {
    public mail_item() {}
    
    private int _resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"mail_item_list")]
  public partial class mail_item_list : global::ProtoBuf.IExtensible
  {
    public mail_item_list() {}
    
    private readonly global::System.Collections.Generic.List<mail_item> _ItemList = new global::System.Collections.Generic.List<mail_item>();
    [global::ProtoBuf.ProtoMember(1, Name=@"ItemList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<mail_item> ItemList
    {
      get { return _ItemList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_mail_state")]
  public partial class request_mail_state : global::ProtoBuf.IExtensible
  {
    public request_mail_state() {}
    
    private MSGGuild _mailguid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mailguid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public MSGGuild mailguid
    {
      get { return _mailguid; }
      set { _mailguid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_mail_state")]
  public partial class respond_mail_state : global::ProtoBuf.IExtensible
  {
    public respond_mail_state() {}
    
    private int _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_load_mail")]
  public partial class request_load_mail : global::ProtoBuf.IExtensible
  {
    public request_load_mail() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_load_mail")]
  public partial class respond_load_mail : global::ProtoBuf.IExtensible
  {
    public respond_load_mail() {}
    

    private player_mail_list _mail_lists = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mail_lists", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public player_mail_list mail_lists
    {
      get { return _mail_lists; }
      set { _mail_lists = value; }
    }
    private int _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}