//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_challenge_stage.hxx
// Note: requires additional types generated from: message_item.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"challenge_stage_floor_info")]
  public partial class challenge_stage_floor_info : global::ProtoBuf.IExtensible
  {
    public challenge_stage_floor_info() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private uint _maxscore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxscore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxscore
    {
      get { return _maxscore; }
      set { _maxscore = value; }
    }
    private bool _achieve_one;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"achieve_one", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool achieve_one
    {
      get { return _achieve_one; }
      set { _achieve_one = value; }
    }
    private bool _achieve_two;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"achieve_two", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool achieve_two
    {
      get { return _achieve_two; }
      set { _achieve_two = value; }
    }
    private bool _achieve_three;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"achieve_three", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool achieve_three
    {
      get { return _achieve_three; }
      set { _achieve_three = value; }
    }
    private uint _day_maxscore;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"day_maxscore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint day_maxscore
    {
      get { return _day_maxscore; }
      set { _day_maxscore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"role_challenge_stage_info")]
  public partial class role_challenge_stage_info : global::ProtoBuf.IExtensible
  {
    public role_challenge_stage_info() {}
    
    private uint _week_score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"week_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint week_score
    {
      get { return _week_score; }
      set { _week_score = value; }
    }
    private uint _currentfloor;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"currentfloor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint currentfloor
    {
      get { return _currentfloor; }
      set { _currentfloor = value; }
    }
    private uint _maxfloor;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxfloor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxfloor
    {
      get { return _maxfloor; }
      set { _maxfloor = value; }
    }
    private readonly global::System.Collections.Generic.List<challenge_stage_floor_info> _floors = new global::System.Collections.Generic.List<challenge_stage_floor_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"floors", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<challenge_stage_floor_info> floors
    {
      get { return _floors; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_challenge_stage_begin")]
  public partial class request_challenge_stage_begin : global::ProtoBuf.IExtensible
  {
    public request_challenge_stage_begin() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_challenge_stage_begin")]
  public partial class respond_challenge_stage_begin : global::ProtoBuf.IExtensible
  {
    public respond_challenge_stage_begin() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }

    private int _scene_resid = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"scene_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int scene_resid
    {
      get { return _scene_resid; }
      set { _scene_resid = value; }
    }

    private int _errorcode = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_challenge_stage_end")]
  public partial class request_challenge_stage_end : global::ProtoBuf.IExtensible
  {
    public request_challenge_stage_end() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }

    private uint _time = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_challenge_stage_end")]
  public partial class respond_challenge_stage_end : global::ProtoBuf.IExtensible
  {
    public respond_challenge_stage_end() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private bool _complete_one;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"complete_one", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool complete_one
    {
      get { return _complete_one; }
      set { _complete_one = value; }
    }
    private bool _complete_two;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"complete_two", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool complete_two
    {
      get { return _complete_two; }
      set { _complete_two = value; }
    }
    private bool _complete_three;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"complete_three", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool complete_three
    {
      get { return _complete_three; }
      set { _complete_three = value; }
    }
    private uint _historty_score;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"historty_score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint historty_score
    {
      get { return _historty_score; }
      set { _historty_score = value; }
    }
    private bool _first_day;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"first_day", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool first_day
    {
      get { return _first_day; }
      set { _first_day = value; }
    }
    private readonly global::System.Collections.Generic.List<award_item_info> _award = new global::System.Collections.Generic.List<award_item_info>();
    [global::ProtoBuf.ProtoMember(8, Name=@"award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<award_item_info> award
    {
      get { return _award; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_challenge_stage_continue")]
  public partial class request_challenge_stage_continue : global::ProtoBuf.IExtensible
  {
    public request_challenge_stage_continue() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_challenge_stage_continue")]
  public partial class respond_challenge_stage_continue : global::ProtoBuf.IExtensible
  {
    public respond_challenge_stage_continue() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private bool _may;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"may", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool may
    {
      get { return _may; }
      set { _may = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"challenge_stage_sweep_floor_award")]
  public partial class challenge_stage_sweep_floor_award : global::ProtoBuf.IExtensible
  {
    public challenge_stage_sweep_floor_award() {}
    
    private uint _floor;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"floor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint floor
    {
      get { return _floor; }
      set { _floor = value; }
    }
    private readonly global::System.Collections.Generic.List<award_item_info> _award = new global::System.Collections.Generic.List<award_item_info>();
    [global::ProtoBuf.ProtoMember(8, Name=@"award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<award_item_info> award
    {
      get { return _award; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_challenge_stage_sweep")]
  public partial class request_challenge_stage_sweep : global::ProtoBuf.IExtensible
  {
    public request_challenge_stage_sweep() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_challenge_stage_sweep")]
  public partial class respond_challenge_stage_sweep : global::ProtoBuf.IExtensible
  {
    public respond_challenge_stage_sweep() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }

    private role_challenge_stage_info _challengeinfo = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"challengeinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public role_challenge_stage_info challengeinfo
    {
      get { return _challengeinfo; }
      set { _challengeinfo = value; }
    }
    private readonly global::System.Collections.Generic.List<challenge_stage_sweep_floor_award> _awards = new global::System.Collections.Generic.List<challenge_stage_sweep_floor_award>();
    [global::ProtoBuf.ProtoMember(3, Name=@"awards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<challenge_stage_sweep_floor_award> awards
    {
      get { return _awards; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}