//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_qianglindanyu.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_qianglindanyu_report_score")]
  public partial class request_qianglindanyu_report_score : global::ProtoBuf.IExtensible
  {
    public request_qianglindanyu_report_score() {}
    
    private uint _score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"qianglindanyu_role_info")]
  public partial class qianglindanyu_role_info : global::ProtoBuf.IExtensible
  {
    public qianglindanyu_role_info() {}
    
    private string _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_qianglindanyu_report_score")]
  public partial class respond_qianglindanyu_report_score : global::ProtoBuf.IExtensible
  {
    public respond_qianglindanyu_report_score() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _playercount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playercount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint playercount
    {
      get { return _playercount; }
      set { _playercount = value; }
    }
    private readonly global::System.Collections.Generic.List<qianglindanyu_role_info> _sortinfo = new global::System.Collections.Generic.List<qianglindanyu_role_info>();
    [global::ProtoBuf.ProtoMember(4, Name=@"sortinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<qianglindanyu_role_info> sortinfo
    {
      get { return _sortinfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_qianglindanyu_over")]
  public partial class request_qianglindanyu_over : global::ProtoBuf.IExtensible
  {
    public request_qianglindanyu_over() {}
    
    private uint _score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"qianglindanyu_item_award")]
  public partial class qianglindanyu_item_award : global::ProtoBuf.IExtensible
  {
    public qianglindanyu_item_award() {}
    
    private int _resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private int _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num; }
      set { _num = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_qianglindanyu_over")]
  public partial class respond_qianglindanyu_over : global::ProtoBuf.IExtensible
  {
    public respond_qianglindanyu_over() {}
    
    private bool _succeed;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"succeed", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool succeed
    {
      get { return _succeed; }
      set { _succeed = value; }
    }
    private uint _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _maxscore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"maxscore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxscore
    {
      get { return _maxscore; }
      set { _maxscore = value; }
    }
    private readonly global::System.Collections.Generic.List<qianglindanyu_item_award> _item_award = new global::System.Collections.Generic.List<qianglindanyu_item_award>();
    [global::ProtoBuf.ProtoMember(4, Name=@"item_award", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<qianglindanyu_item_award> item_award
    {
      get { return _item_award; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}