//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: message_weapon_depot.hxx
// Note: requires additional types generated from: message_item.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_buy_weapon")]
  public partial class request_buy_weapon : global::ProtoBuf.IExtensible
  {
    public request_buy_weapon() {}
    
    private uint _resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint resid
    {
      get { return _resid; }
      set { _resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_buy_weapon")]
  public partial class respond_buy_weapon : global::ProtoBuf.IExtensible
  {
    public respond_buy_weapon() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_change_weapon")]
  public partial class request_change_weapon : global::ProtoBuf.IExtensible
  {
    public request_change_weapon() {}
    
    private int _main_weapon_resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"main_weapon_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int main_weapon_resid
    {
      get { return _main_weapon_resid; }
      set { _main_weapon_resid = value; }
    }
    private int _sub_weapon_resid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sub_weapon_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sub_weapon_resid
    {
      get { return _sub_weapon_resid; }
      set { _sub_weapon_resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_change_weapon")]
  public partial class respond_change_weapon : global::ProtoBuf.IExtensible
  {
    public respond_change_weapon() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private int _main_weapon_resid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"main_weapon_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int main_weapon_resid
    {
      get { return _main_weapon_resid; }
      set { _main_weapon_resid = value; }
    }
    private int _sub_weapon_resid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sub_weapon_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int sub_weapon_resid
    {
      get { return _sub_weapon_resid; }
      set { _sub_weapon_resid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_stren_weapon")]
  public partial class request_stren_weapon : global::ProtoBuf.IExtensible
  {
    public request_stren_weapon() {}
    
    private uint _money_stren_cost;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"money_stren_cost", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint money_stren_cost
    {
      get { return _money_stren_cost; }
      set { _money_stren_cost = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_stren_weapon")]
  public partial class respond_stren_weapon : global::ProtoBuf.IExtensible
  {
    public respond_stren_weapon() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_set_promote")]
  public partial class request_set_promote : global::ProtoBuf.IExtensible
  {
    public request_set_promote() {}
    
    private int _weapon_resid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"weapon_resid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weapon_resid
    {
      get { return _weapon_resid; }
      set { _weapon_resid = value; }
    }
    private int _weapon_pos;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"weapon_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int weapon_pos
    {
      get { return _weapon_pos; }
      set { _weapon_pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_set_promote")]
  public partial class respond_set_promote : global::ProtoBuf.IExtensible
  {
    public respond_set_promote() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"request_bap_fittings")]
  public partial class request_bap_fittings : global::ProtoBuf.IExtensible
  {
    public request_bap_fittings() {}
    
    private uint _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _mproperty = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"mproperty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mproperty
    {
      get { return _mproperty; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _mvalue = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"mvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> mvalue
    {
      get { return _mvalue; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _mlock = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(4, Name=@"mlock", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<bool> mlock
    {
      get { return _mlock; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _start = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"start", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> start
    {
      get { return _start; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _end = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(6, Name=@"end", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> end
    {
      get { return _end; }
    }
  
    private uint _price;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint price
    {
      get { return _price; }
      set { _price = value; }
    }
    private uint _itemId;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId; }
      set { _itemId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"respond_bap_fittings")]
  public partial class respond_bap_fittings : global::ProtoBuf.IExtensible
  {
    public respond_bap_fittings() {}
    
    private int _errorcode;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"errorcode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int errorcode
    {
      get { return _errorcode; }
      set { _errorcode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}