//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: errorcode.hxx
namespace Message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"error_code")]
  public partial class error_code : global::ProtoBuf.IExtensible
  {
    public error_code() {}
    
    private int _ingore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ingore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ingore
    {
      get { return _ingore; }
      set { _ingore = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ERROR_CODE")]
    public enum ERROR_CODE
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOGIN_BEING", Value=10000)]
      ERR_LOGIN_BEING = 10000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOGIN_USER_OR_PASSWD_ERROR", Value=10001)]
      ERR_LOGIN_USER_OR_PASSWD_ERROR = 10001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOGIN_OK", Value=10002)]
      ERR_LOGIN_OK = 10002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOGIN_FAILED_CLIENT_VERSION", Value=10003)]
      ERR_LOGIN_FAILED_CLIENT_VERSION = 10003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_LOGIN_END", Value=11000)]
      ERR_LOGIN_END = 11000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CREATE_ROLE_BEGIN", Value=11001)]
      ERR_CREATE_ROLE_BEGIN = 11001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CREATE_OK", Value=11002)]
      ERR_CREATE_OK = 11002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CREATE_FAILED_NAME", Value=11003)]
      ERR_CREATE_FAILED_NAME = 11003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CREATE_FAILED_MAX_COUNT", Value=11004)]
      ERR_CREATE_FAILED_MAX_COUNT = 11004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CREATE_FAILED_CORE", Value=11005)]
      ERR_CREATE_FAILED_CORE = 11005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CREATE_FAILED_NAME_TOO_LONG", Value=11006)]
      ERR_CREATE_FAILED_NAME_TOO_LONG = 11006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CREATE_ROLE_END", Value=12000)]
      ERR_CREATE_ROLE_END = 12000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ENTER_GAME_OK", Value=12001)]
      ERR_ENTER_GAME_OK = 12001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ENTER_GAME_FAILED", Value=12020)]
      ERR_ENTER_GAME_FAILED = 12020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_SYSTEM", Value=130000)]
      ERR_SCENE_SYSTEM = 130000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_ENTER_OK", Value=130010)]
      ERR_SCENE_ENTER_OK = 130010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_ENTER_FAILED", Value=130011)]
      ERR_SCENE_ENTER_FAILED = 130011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_ENTER_FAILED_LOCKED", Value=130012)]
      ERR_SCENE_ENTER_FAILED_LOCKED = 130012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_ENTER_FAILED_NOCOST", Value=130013)]
      ERR_SCENE_ENTER_FAILED_NOCOST = 130013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_ENTER_FAILED_NOTIMES", Value=130014)]
      ERR_SCENE_ENTER_FAILED_NOTIMES = 130014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_ENTER_FAILED_NOSP", Value=130015)]
      ERR_SCENE_ENTER_FAILED_NOSP = 130015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_ENTER_FAILED_RAND_AWARD", Value=130016)]
      ERR_SCENE_ENTER_FAILED_RAND_AWARD = 130016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_PASS_OK", Value=130020)]
      ERR_SCENE_PASS_OK = 130020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_PASS_FAILED", Value=130021)]
      ERR_SCENE_PASS_FAILED = 130021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_PASS_FAILED_LOCKED", Value=130022)]
      ERR_SCENE_PASS_FAILED_LOCKED = 130022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_PASS_FAILED_NOSP", Value=130023)]
      ERR_SCENE_PASS_FAILED_NOSP = 130023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_PASS_FAILED_AWARD_NOCOST", Value=130024)]
      ERR_SCENE_PASS_FAILED_AWARD_NOCOST = 130024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_PASS_FAILED_NOTIMES", Value=130025)]
      ERR_SCENE_PASS_FAILED_NOTIMES = 130025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_AWARD_OK", Value=130030)]
      ERR_SCENE_AWARD_OK = 130030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_AWARD_FAILED", Value=130031)]
      ERR_SCENE_AWARD_FAILED = 130031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_RELIVE_OK", Value=130040)]
      ERR_SCENE_RELIVE_OK = 130040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_RELIVE_FAILED_NOCOST", Value=130041)]
      ERR_SCENE_RELIVE_FAILED_NOCOST = 130041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_RELIVE_FAILED_NOTIMES", Value=130042)]
      ERR_SCENE_RELIVE_FAILED_NOTIMES = 130042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_RELIVE_FAILED", Value=130043)]
      ERR_SCENE_RELIVE_FAILED = 130043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_UNLOCK_OK", Value=130050)]
      ERR_SCENE_UNLOCK_OK = 130050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SCENE_UNLOCK_FAILED", Value=130051)]
      ERR_SCENE_UNLOCK_FAILED = 130051,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_REFRESH_OK", Value=131000)]
      ERR_ARENA_REFRESH_OK = 131000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_REFRESH_FAILED", Value=131001)]
      ERR_ARENA_REFRESH_FAILED = 131001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BEGIN_OK", Value=131010)]
      ERR_ARENA_BEGIN_OK = 131010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BEGIN_FAILED", Value=131011)]
      ERR_ARENA_BEGIN_FAILED = 131011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BEGIN_FAILED_NOTIMES", Value=131012)]
      ERR_ARENA_BEGIN_FAILED_NOTIMES = 131012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BEGIN_FAILED_CD", Value=131013)]
      ERR_ARENA_BEGIN_FAILED_CD = 131013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_END_OK", Value=131020)]
      ERR_ARENA_END_OK = 131020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_END_FAILED", Value=131021)]
      ERR_ARENA_END_FAILED = 131021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_END_FAILED_NOTIMES", Value=131022)]
      ERR_ARENA_END_FAILED_NOTIMES = 131022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_END_FAILED_CD", Value=131023)]
      ERR_ARENA_END_FAILED_CD = 131023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_RECORD_OK", Value=131030)]
      ERR_ARENA_RECORD_OK = 131030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_RECORD_FAILED", Value=131031)]
      ERR_ARENA_RECORD_FAILED = 131031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BUYTIMES_OK", Value=131040)]
      ERR_ARENA_BUYTIMES_OK = 131040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BUYTIMES_FAILED", Value=131041)]
      ERR_ARENA_BUYTIMES_FAILED = 131041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BUYTIMES_FAILED_NOCOST", Value=131042)]
      ERR_ARENA_BUYTIMES_FAILED_NOCOST = 131042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ARENA_BUYTIMES_FAILED_NOTIMES", Value=131043)]
      ERR_ARENA_BUYTIMES_FAILED_NOTIMES = 131043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_LIST_OK", Value=132000)]
      ERR_QUALIFYING_LIST_OK = 132000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_LIST_FAILED", Value=132001)]
      ERR_QUALIFYING_LIST_FAILED = 132001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BEGIN_OK", Value=132010)]
      ERR_QUALIFYING_BEGIN_OK = 132010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BEGIN_FAILED", Value=132011)]
      ERR_QUALIFYING_BEGIN_FAILED = 132011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BEGIN_FAILED_NOTIMES", Value=132012)]
      ERR_QUALIFYING_BEGIN_FAILED_NOTIMES = 132012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BEGIN_FAILED_CD", Value=132013)]
      ERR_QUALIFYING_BEGIN_FAILED_CD = 132013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BEGIN_FAILED_SELF", Value=132014)]
      ERR_QUALIFYING_BEGIN_FAILED_SELF = 132014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_END_OK", Value=132020)]
      ERR_QUALIFYING_END_OK = 132020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_END_FAILED", Value=132021)]
      ERR_QUALIFYING_END_FAILED = 132021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_END_FAILED_NOTIMES", Value=132022)]
      ERR_QUALIFYING_END_FAILED_NOTIMES = 132022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_END_FAILED_CD", Value=132023)]
      ERR_QUALIFYING_END_FAILED_CD = 132023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_RECORD_OK", Value=132030)]
      ERR_QUALIFYING_RECORD_OK = 132030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_RECORD_FAILED", Value=132031)]
      ERR_QUALIFYING_RECORD_FAILED = 132031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BUYTIMES_OK", Value=132040)]
      ERR_QUALIFYING_BUYTIMES_OK = 132040,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BUYTIMES_FAILED", Value=132041)]
      ERR_QUALIFYING_BUYTIMES_FAILED = 132041,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BUYTIMES_FAILED_NOCOST", Value=132042)]
      ERR_QUALIFYING_BUYTIMES_FAILED_NOCOST = 132042,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_BUYTIMES_FAILED_NOTIMES", Value=132043)]
      ERR_QUALIFYING_BUYTIMES_FAILED_NOTIMES = 132043,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUALIFYING_LOCKED_AND_AWARD", Value=132050)]
      ERR_QUALIFYING_LOCKED_AND_AWARD = 132050,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WEAPON_DEPOT_BEGIN", Value=140000)]
      ERR_WEAPON_DEPOT_BEGIN = 140000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_OK", Value=140001)]
      ERR_WD_BUY_OK = 140001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_NO_GAMEMONEY", Value=140002)]
      ERR_WD_BUY_NO_GAMEMONEY = 140002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_NO_RMB", Value=140003)]
      ERR_WD_BUY_NO_RMB = 140003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_NO_PRESTIGE", Value=140004)]
      ERR_WD_BUY_NO_PRESTIGE = 140004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_HAVE", Value=140005)]
      ERR_WD_BUY_HAVE = 140005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_INVALID_RESID", Value=140006)]
      ERR_WD_BUY_INVALID_RESID = 140006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_FAILED", Value=140007)]
      ERR_WD_BUY_FAILED = 140007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BUY_BAG_FULL", Value=140008)]
      ERR_WD_BUY_BAG_FULL = 140008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_CHANGE_WEAPON_OK", Value=140009)]
      ERR_WD_CHANGE_WEAPON_OK = 140009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_CHANGE_WEAPON_FAILED", Value=140010)]
      ERR_WD_CHANGE_WEAPON_FAILED = 140010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_STREN_WEAPON_OK", Value=140011)]
      ERR_WD_STREN_WEAPON_OK = 140011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_STREN_WEAPON_FAILED", Value=140012)]
      ERR_WD_STREN_WEAPON_FAILED = 140012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_SET_PROMOTE_OK", Value=140013)]
      ERR_WD_SET_PROMOTE_OK = 140013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_SET_PROMOTE_FAILED", Value=140014)]
      ERR_WD_SET_PROMOTE_FAILED = 140014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BAP_FITTINGS_OK", Value=140015)]
      ERR_WD_BAP_FITTINGS_OK = 140015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WD_BAP_FITTINGS_FAILED", Value=140016)]
      ERR_WD_BAP_FITTINGS_FAILED = 140016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WEAPON_DEPOT_END", Value=145000)]
      ERR_WEAPON_DEPOT_END = 145000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CHALLENGE_STAGE_ENTER_STAGE_FAILED", Value=145001)]
      ERR_CHALLENGE_STAGE_ENTER_STAGE_FAILED = 145001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CHALLENGE_STAGE_ENTER_STAGE_OK", Value=145100)]
      ERR_CHALLENGE_STAGE_ENTER_STAGE_OK = 145100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CHALLENGE_RANKING_OK", Value=145002)]
      ERR_CHALLENGE_RANKING_OK = 145002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CHALLENGE_RANKING_FAILED", Value=145003)]
      ERR_CHALLENGE_RANKING_FAILED = 145003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SKILL_OK", Value=150000)]
      ERR_SKILL_OK = 150000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SKILL_LEVEL_NO_MONEY", Value=150001)]
      ERR_SKILL_LEVEL_NO_MONEY = 150001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SKILL_LEVEL_NO_LEVEL", Value=150002)]
      ERR_SKILL_LEVEL_NO_LEVEL = 150002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SKILL_LEVEL_MAX_LEVEL", Value=150003)]
      ERR_SKILL_LEVEL_MAX_LEVEL = 150003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SKILL_FAILED", Value=150004)]
      ERR_SKILL_FAILED = 150004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUEST_ACCEPT_OK", Value=160000)]
      ERR_QUEST_ACCEPT_OK = 160000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUEST_ACCEPT_FAILED", Value=160001)]
      ERR_QUEST_ACCEPT_FAILED = 160001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUEST_FINISH_OK", Value=160002)]
      ERR_QUEST_FINISH_OK = 160002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUEST_FINISH_FAILED", Value=160003)]
      ERR_QUEST_FINISH_FAILED = 160003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_QUEST_SYSTEM", Value=160004)]
      ERR_QUEST_SYSTEM = 160004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_ACTIVE_OK", Value=160005)]
      ERR_WING_ACTIVE_OK = 160005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_ACTIVE_FAILED", Value=160006)]
      ERR_WING_ACTIVE_FAILED = 160006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_FORGE_OK", Value=160007)]
      ERR_WING_FORGE_OK = 160007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_FORGE_FAILED", Value=160008)]
      ERR_WING_FORGE_FAILED = 160008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_FORGE_ITEM_NO_ENOUGH", Value=160009)]
      ERR_WING_FORGE_ITEM_NO_ENOUGH = 160009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_EQUIP_OK", Value=160010)]
      ERR_WING_EQUIP_OK = 160010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_EQUIP_FAILED", Value=160011)]
      ERR_WING_EQUIP_FAILED = 160011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_SYSTEM", Value=160012)]
      ERR_WING_SYSTEM = 160012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_UPDATE_OK", Value=160013)]
      ERR_WING_UPDATE_OK = 160013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_UPDATE_FAILED", Value=160014)]
      ERR_WING_UPDATE_FAILED = 160014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_TAKEOFF_OK", Value=160015)]
      ERR_WING_TAKEOFF_OK = 160015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_WING_TAKEOFF_FAILED", Value=160016)]
      ERR_WING_TAKEOFF_FAILED = 160016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FASHION_ACTIVE_OK", Value=160017)]
      ERR_FASHION_ACTIVE_OK = 160017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FASHION_ACTIVE_FAILED", Value=160018)]
      ERR_FASHION_ACTIVE_FAILED = 160018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FASHION_ITEM_NO_ENOUGH", Value=160019)]
      ERR_FASHION_ITEM_NO_ENOUGH = 160019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FASHION_EQUIP_OK", Value=160020)]
      ERR_FASHION_EQUIP_OK = 160020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FASHION_EQUIP_FAILED", Value=160021)]
      ERR_FASHION_EQUIP_FAILED = 160021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FASHION_ADDSTAR_OK", Value=160022)]
      ERR_FASHION_ADDSTAR_OK = 160022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FASHION_ADDSTAR_FAILED", Value=160023)]
      ERR_FASHION_ADDSTAR_FAILED = 160023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MALL_OK", Value=170000)]
      ERR_MALL_OK = 170000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MALL_BUY_NO_MONEY", Value=170001)]
      ERR_MALL_BUY_NO_MONEY = 170001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MALL_BUY_NO_TIMES", Value=170002)]
      ERR_MALL_BUY_NO_TIMES = 170002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MALL_FAILED", Value=170003)]
      ERR_MALL_FAILED = 170003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_BEGIN", Value=180000)]
      ERR_DEFENCE_BEGIN = 180000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STREN_OK", Value=180001)]
      ERR_DEFENCE_STREN_OK = 180001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STREN_FAILED", Value=180002)]
      ERR_DEFENCE_STREN_FAILED = 180002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_RISING_STARS_OK", Value=180003)]
      ERR_DEFENCE_RISING_STARS_OK = 180003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_RISING_STARS_FAILED", Value=180004)]
      ERR_DEFENCE_RISING_STARS_FAILED = 180004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_PROMOTE_OK", Value=180005)]
      ERR_DEFENCE_PROMOTE_OK = 180005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_PROMOTE_FAILED", Value=180006)]
      ERR_DEFENCE_PROMOTE_FAILED = 180006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STONE_INLAY_OK", Value=180007)]
      ERR_DEFENCE_STONE_INLAY_OK = 180007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STONE_INLAY_FAILED", Value=180008)]
      ERR_DEFENCE_STONE_INLAY_FAILED = 180008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STONE_UNINLAY_OK", Value=180009)]
      ERR_DEFENCE_STONE_UNINLAY_OK = 180009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STONE_UNINLAY_FAILED", Value=180010)]
      ERR_DEFENCE_STONE_UNINLAY_FAILED = 180010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STONE_COMB_OK", Value=180011)]
      ERR_DEFENCE_STONE_COMB_OK = 180011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STONE_NOT_EQUIPED_COMB_OK", Value=180012)]
      ERR_DEFENCE_STONE_NOT_EQUIPED_COMB_OK = 180012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_STONE_COMB_FAILED", Value=180013)]
      ERR_DEFENCE_STONE_COMB_FAILED = 180013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_DEFENCE_SALE_OK", Value=180014)]
      ERR_DEFENCE_DEFENCE_SALE_OK = 180014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_DEFENCE_SALE_FAILED", Value=180015)]
      ERR_DEFENCE_DEFENCE_SALE_FAILED = 180015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_DEFENCE_END", Value=185000)]
      ERR_DEFENCE_END = 185000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACTIVITY_BEGIN", Value=185001)]
      ERR_ACTIVITY_BEGIN = 185001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACTIVITY_JOIN_FAIL", Value=185002)]
      ERR_ACTIVITY_JOIN_FAIL = 185002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACTIVITY_JOIN_ONOPEN", Value=185003)]
      ERR_ACTIVITY_JOIN_ONOPEN = 185003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACTIVITY_JOIN_HAS_COMPLETE", Value=185004)]
      ERR_ACTIVITY_JOIN_HAS_COMPLETE = 185004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACTIVITY_JOIN_NO_TIME", Value=185005)]
      ERR_ACTIVITY_JOIN_NO_TIME = 185005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACTIVITY_JOIN_OK", Value=185006)]
      ERR_ACTIVITY_JOIN_OK = 185006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ACTIVITY_END", Value=185100)]
      ERR_ACTIVITY_END = 185100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_EQUIP_ITEM_OK", Value=190000)]
      ERR_EQUIP_ITEM_OK = 190000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_EQUIP_ITEM_FAIL", Value=190001)]
      ERR_EQUIP_ITEM_FAIL = 190001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SALE_ITEM_OK", Value=190002)]
      ERR_SALE_ITEM_OK = 190002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SALE_ITEM_FAILED", Value=190003)]
      ERR_SALE_ITEM_FAILED = 190003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_BAG_OP_OK", Value=200000)]
      ERR_BAG_OP_OK = 200000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_BAG_OP_FAIL", Value=200001)]
      ERR_BAG_OP_FAIL = 200001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SHOP_OK", Value=210000)]
      ERR_SHOP_OK = 210000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_SHOP_FAILED", Value=210001)]
      ERR_SHOP_FAILED = 210001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_RANKING_OK", Value=220000)]
      ERR_RANKING_OK = 220000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_RANKING_FAILED", Value=220001)]
      ERR_RANKING_FAILED = 220001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_EGG_OK", Value=230000)]
      ERR_EGG_OK = 230000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_EGG_FAILED", Value=230001)]
      ERR_EGG_FAILED = 230001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CHALLENGE_SWEEP_OK", Value=230010)]
      ERR_CHALLENGE_SWEEP_OK = 230010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CHALLENGE_SWEEP_FAILED_NO_ITEM", Value=230011)]
      ERR_CHALLENGE_SWEEP_FAILED_NO_ITEM = 230011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_OPEN_OK", Value=230020)]
      ERR_MAIL_OPEN_OK = 230020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_OPEN_FAILED", Value=230021)]
      ERR_MAIL_OPEN_FAILED = 230021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_PICK_OK", Value=230022)]
      ERR_MAIL_PICK_OK = 230022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_PICK_FAILED", Value=230023)]
      ERR_MAIL_PICK_FAILED = 230023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_DELETE_OK", Value=230024)]
      ERR_MAIL_DELETE_OK = 230024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_DELETE_FAILED", Value=230025)]
      ERR_MAIL_DELETE_FAILED = 230025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_LOAD_OK", Value=230026)]
      ERR_MAIL_LOAD_OK = 230026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_MAIL_LOAD_FAILED", Value=230027)]
      ERR_MAIL_LOAD_FAILED = 230027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_TITLE_OK", Value=240000)]
      ERR_TITLE_OK = 240000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_TITLE_FAILED", Value=240001)]
      ERR_TITLE_FAILED = 240001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_REWARD_OK", Value=250000)]
      ERR_ZONE_REWARD_OK = 250000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_REWARD_FULL_BAG", Value=250001)]
      ERR_ZONE_REWARD_FULL_BAG = 250001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_REWARD_AGAIN", Value=250002)]
      ERR_ZONE_REWARD_AGAIN = 250002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_ZONE_DATA_FAILED", Value=250003)]
      ERR_ZONE_DATA_FAILED = 250003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CROPS_BUY_OK", Value=260000)]
      ERR_CROPS_BUY_OK = 260000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CROPS_BUY_FALIED", Value=260001)]
      ERR_CROPS_BUY_FALIED = 260001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CROPS_CHANGE_OK", Value=260002)]
      ERR_CROPS_CHANGE_OK = 260002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CROPS_CHANGE_FAILED", Value=260003)]
      ERR_CROPS_CHANGE_FAILED = 260003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CROPS_PROMOTE_OK", Value=260004)]
      ERR_CROPS_PROMOTE_OK = 260004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_CROPS_PROMOTE_FAILED", Value=260005)]
      ERR_CROPS_PROMOTE_FAILED = 260005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_BAG_ADD_ITEM_ERROR", Value=300000)]
      ERROR_BAG_ADD_ITEM_ERROR = 300000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR_BAG_ADD_ITEM_MAIL_TO", Value=300001)]
      ERROR_BAG_ADD_ITEM_MAIL_TO = 300001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FUND_OK", Value=310000)]
      ERR_FUND_OK = 310000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_FUND_FAILED", Value=310001)]
      ERR_FUND_FAILED = 310001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_OTHER_OK", Value=320010)]
      ERR_OTHER_OK = 320010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_OTHER_FAILED", Value=320012)]
      ERR_OTHER_FAILED = 320012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_TOTALCHARGE_REWARD_OK", Value=330000)]
      ERR_TOTALCHARGE_REWARD_OK = 330000,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_TOTALCHARGE_REWARD_FAILED", Value=330001)]
      ERR_TOTALCHARGE_REWARD_FAILED = 330001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_OPEN_BOX_ITEM_OK", Value=330010)]
      ERR_OPEN_BOX_ITEM_OK = 330010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERR_OPEN_BOX_ITEM_FAILDD", Value=330011)]
      ERR_OPEN_BOX_ITEM_FAILDD = 330011
    }
  
}